/* Generated by Yosys 0.33+34 (git sha1 b84ed5d3a, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_cust_tile_test/inputs/custmul.v:1.1-38.10" *)
module custmuleg(IN, OUT, clk);
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_cust_tile_test/inputs/custmul.v:3.19-3.21" *)
  input [127:0] IN;
  wire [127:0] IN;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_cust_tile_test/inputs/custmul.v:9.14-9.15" *)
  wire [15:0] O;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_cust_tile_test/inputs/custmul.v:4.21-4.24" *)
  output [127:0] OUT;
  wire [127:0] OUT;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_cust_tile_test/inputs/custmul.v:10.9-10.11" *)
  reg R0;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_cust_tile_test/inputs/custmul.v:10.13-10.17" *)
  reg R0_1;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_cust_tile_test/inputs/custmul.v:5.11-5.14" *)
  input clk;
  wire clk;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_cust_tile_test/inputs/custmul.v:31.2-34.5" *)
  always @(posedge clk)
    R0 <= R0_1;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_cust_tile_test/inputs/custmul.v:31.2-34.5" *)
  always @(posedge clk)
    R0_1 <= IN[0];
  (* module_not_derived = 32'd1 *)
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_cust_tile_test/inputs/custmul.v:24.7-29.6" *)
  custmul #(
    .MODE_CUSTMUL(32'sd1)
  ) cmul (
    .C(clk),
    .I0(IN[15:0]),
    .I1(IN[47:32]),
    .Q(O)
  );
  assign OUT = { O, 110'hxxxxxxxxxxxxxxxxxxxxxxxxxxxx, R0, R0_1 };
endmodule
