// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module fqmul

module CustMulBlock(	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
  input         IPIN_0,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_1,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_2,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_3,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_4,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_5,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_6,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_7,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_8,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_9,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_10,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_11,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_12,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_13,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_14,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_15,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_16,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_17,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_18,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_19,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_20,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_21,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_22,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_23,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_24,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_25,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_26,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_27,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_28,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_29,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_30,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
                IPIN_31,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:20:12
  output        OPIN_32,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_33,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_34,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_35,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_36,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_37,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_38,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_39,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_40,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_41,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_42,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_43,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_44,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_45,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_46,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
                OPIN_47,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:23:12
  input         clock,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:25:33
                reset,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:26:33
  input  [31:0] configBits,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:28:37
  input         loopBreak,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:29:36
                pathBreak,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:30:36
                gndLBouts	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:31:36
);

  wire [15:0] _custMul_c_out_mul;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23
  wire        _LBIns_T_1 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_0;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_3 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_1;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_5 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_2;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_7 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_3;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_9 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_4;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_11 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_5;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_13 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_6;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_15 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_7;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_17 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_8;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_19 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_9;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_21 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_10;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_23 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_11;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_25 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_12;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_27 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_13;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_29 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_14;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_31 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_15;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_33 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_16;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_35 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_17;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_37 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_18;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_39 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_19;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_41 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_20;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_43 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_21;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_45 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_22;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_47 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_23;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_49 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_24;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_51 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_25;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_53 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_26;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_55 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_27;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_57 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_28;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_59 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_29;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_61 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_30;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _LBIns_T_63 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:{37,42}
  reg         LBIns_pb_IPIN_FF_31;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_32_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_32_pb_OPIN_FF_0;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_33_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_33_pb_OPIN_FF_1;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_34_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_34_pb_OPIN_FF_2;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_35_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_35_pb_OPIN_FF_3;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_36_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_36_pb_OPIN_FF_4;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_37_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_37_pb_OPIN_FF_5;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_38_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_38_pb_OPIN_FF_6;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_39_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_39_pb_OPIN_FF_7;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_40_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_40_pb_OPIN_FF_8;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_41_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_41_pb_OPIN_FF_9;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_42_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_42_pb_OPIN_FF_10;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_43_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_43_pb_OPIN_FF_11;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_44_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_44_pb_OPIN_FF_12;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_45_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_45_pb_OPIN_FF_13;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_46_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_46_pb_OPIN_FF_14;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        _OPIN_47_T_2 = configBits[31] | pathBreak;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:37, :50:59
  reg         OPIN_47_pb_OPIN_FF_15;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  always @(posedge clock) begin	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:25:33
    if (_LBIns_T_1)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_0 <= IPIN_0;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_3)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_1 <= IPIN_1;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_5)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_2 <= IPIN_2;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_7)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_3 <= IPIN_3;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_9)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_4 <= IPIN_4;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_11)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_5 <= IPIN_5;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_13)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_6 <= IPIN_6;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_15)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_7 <= IPIN_7;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_17)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_8 <= IPIN_8;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_19)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_9 <= IPIN_9;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_21)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_10 <= IPIN_10;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_23)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_11 <= IPIN_11;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_25)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_12 <= IPIN_12;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_27)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_13 <= IPIN_13;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_29)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_14 <= IPIN_14;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_31)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_15 <= IPIN_15;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_33)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_16 <= IPIN_16;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_35)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_17 <= IPIN_17;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_37)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_18 <= IPIN_18;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_39)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_19 <= IPIN_19;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_41)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_20 <= IPIN_20;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_43)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_21 <= IPIN_21;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_45)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_22 <= IPIN_22;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_47)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_23 <= IPIN_23;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_49)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_24 <= IPIN_24;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_51)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_25 <= IPIN_25;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_53)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_26 <= IPIN_26;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_55)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_27 <= IPIN_27;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_57)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_28 <= IPIN_28;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_59)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_29 <= IPIN_29;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_61)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_30 <= IPIN_30;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_LBIns_T_63)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42
      LBIns_pb_IPIN_FF_31 <= IPIN_31;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_32_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_32_pb_OPIN_FF_0 <= _custMul_c_out_mul[0];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_33_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_33_pb_OPIN_FF_1 <= _custMul_c_out_mul[1];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_34_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_34_pb_OPIN_FF_2 <= _custMul_c_out_mul[2];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_35_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_35_pb_OPIN_FF_3 <= _custMul_c_out_mul[3];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_36_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_36_pb_OPIN_FF_4 <= _custMul_c_out_mul[4];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_37_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_37_pb_OPIN_FF_5 <= _custMul_c_out_mul[5];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_38_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_38_pb_OPIN_FF_6 <= _custMul_c_out_mul[6];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_39_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_39_pb_OPIN_FF_7 <= _custMul_c_out_mul[7];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_40_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_40_pb_OPIN_FF_8 <= _custMul_c_out_mul[8];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_41_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_41_pb_OPIN_FF_9 <= _custMul_c_out_mul[9];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_42_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_42_pb_OPIN_FF_10 <= _custMul_c_out_mul[10];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_43_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_43_pb_OPIN_FF_11 <= _custMul_c_out_mul[11];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_44_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_44_pb_OPIN_FF_12 <= _custMul_c_out_mul[12];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_45_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_45_pb_OPIN_FF_13 <= _custMul_c_out_mul[13];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_46_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_46_pb_OPIN_FF_14 <= _custMul_c_out_mul[14];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    if (_OPIN_47_T_2)	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:50:59
      OPIN_47_pb_OPIN_FF_15 <= _custMul_c_out_mul[15];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23, :50:39, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
      `FIRRTL_BEFORE_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
      automatic logic [31:0] _RANDOM[0:1];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
      `ifdef INIT_RANDOM_PROLOG_	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
        `INIT_RANDOM_PROLOG_	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
        end	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
        LBIns_pb_IPIN_FF_0 = _RANDOM[1'h0][0];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_1 = _RANDOM[1'h0][1];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_2 = _RANDOM[1'h0][2];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_3 = _RANDOM[1'h0][3];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_4 = _RANDOM[1'h0][4];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_5 = _RANDOM[1'h0][5];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_6 = _RANDOM[1'h0][6];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_7 = _RANDOM[1'h0][7];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_8 = _RANDOM[1'h0][8];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_9 = _RANDOM[1'h0][9];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_10 = _RANDOM[1'h0][10];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_11 = _RANDOM[1'h0][11];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_12 = _RANDOM[1'h0][12];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_13 = _RANDOM[1'h0][13];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_14 = _RANDOM[1'h0][14];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_15 = _RANDOM[1'h0][15];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_16 = _RANDOM[1'h0][16];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_17 = _RANDOM[1'h0][17];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_18 = _RANDOM[1'h0][18];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_19 = _RANDOM[1'h0][19];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_20 = _RANDOM[1'h0][20];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_21 = _RANDOM[1'h0][21];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_22 = _RANDOM[1'h0][22];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_23 = _RANDOM[1'h0][23];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_24 = _RANDOM[1'h0][24];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_25 = _RANDOM[1'h0][25];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_26 = _RANDOM[1'h0][26];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_27 = _RANDOM[1'h0][27];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_28 = _RANDOM[1'h0][28];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_29 = _RANDOM[1'h0][29];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_30 = _RANDOM[1'h0][30];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_31 = _RANDOM[1'h0][31];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_32_pb_OPIN_FF_0 = _RANDOM[1'h1][0];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_33_pb_OPIN_FF_1 = _RANDOM[1'h1][1];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_34_pb_OPIN_FF_2 = _RANDOM[1'h1][2];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_35_pb_OPIN_FF_3 = _RANDOM[1'h1][3];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_36_pb_OPIN_FF_4 = _RANDOM[1'h1][4];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_37_pb_OPIN_FF_5 = _RANDOM[1'h1][5];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_38_pb_OPIN_FF_6 = _RANDOM[1'h1][6];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_39_pb_OPIN_FF_7 = _RANDOM[1'h1][7];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_40_pb_OPIN_FF_8 = _RANDOM[1'h1][8];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_41_pb_OPIN_FF_9 = _RANDOM[1'h1][9];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_42_pb_OPIN_FF_10 = _RANDOM[1'h1][10];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_43_pb_OPIN_FF_11 = _RANDOM[1'h1][11];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_44_pb_OPIN_FF_12 = _RANDOM[1'h1][12];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_45_pb_OPIN_FF_13 = _RANDOM[1'h1][13];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_46_pb_OPIN_FF_14 = _RANDOM[1'h1][14];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_47_pb_OPIN_FF_15 = _RANDOM[1'h1][15];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
      `FIRRTL_AFTER_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  fqmul custMul (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:43:23
    .a_in_mul
      ({_LBIns_T_31 ? LBIns_pb_IPIN_FF_15 : IPIN_15,
        _LBIns_T_29 ? LBIns_pb_IPIN_FF_14 : IPIN_14,
        _LBIns_T_27 ? LBIns_pb_IPIN_FF_13 : IPIN_13,
        _LBIns_T_25 ? LBIns_pb_IPIN_FF_12 : IPIN_12,
        _LBIns_T_23 ? LBIns_pb_IPIN_FF_11 : IPIN_11,
        _LBIns_T_21 ? LBIns_pb_IPIN_FF_10 : IPIN_10,
        _LBIns_T_19 ? LBIns_pb_IPIN_FF_9 : IPIN_9,
        _LBIns_T_17 ? LBIns_pb_IPIN_FF_8 : IPIN_8,
        _LBIns_T_15 ? LBIns_pb_IPIN_FF_7 : IPIN_7,
        _LBIns_T_13 ? LBIns_pb_IPIN_FF_6 : IPIN_6,
        _LBIns_T_11 ? LBIns_pb_IPIN_FF_5 : IPIN_5,
        _LBIns_T_9 ? LBIns_pb_IPIN_FF_4 : IPIN_4,
        _LBIns_T_7 ? LBIns_pb_IPIN_FF_3 : IPIN_3,
        _LBIns_T_5 ? LBIns_pb_IPIN_FF_2 : IPIN_2,
        _LBIns_T_3 ? LBIns_pb_IPIN_FF_1 : IPIN_1,
        _LBIns_T_1 ? LBIns_pb_IPIN_FF_0 : IPIN_0}),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42, :40:86, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
    .b_in_mul
      ({_LBIns_T_63 ? LBIns_pb_IPIN_FF_31 : IPIN_31,
        _LBIns_T_61 ? LBIns_pb_IPIN_FF_30 : IPIN_30,
        _LBIns_T_59 ? LBIns_pb_IPIN_FF_29 : IPIN_29,
        _LBIns_T_57 ? LBIns_pb_IPIN_FF_28 : IPIN_28,
        _LBIns_T_55 ? LBIns_pb_IPIN_FF_27 : IPIN_27,
        _LBIns_T_53 ? LBIns_pb_IPIN_FF_26 : IPIN_26,
        _LBIns_T_51 ? LBIns_pb_IPIN_FF_25 : IPIN_25,
        _LBIns_T_49 ? LBIns_pb_IPIN_FF_24 : IPIN_24,
        _LBIns_T_47 ? LBIns_pb_IPIN_FF_23 : IPIN_23,
        _LBIns_T_45 ? LBIns_pb_IPIN_FF_22 : IPIN_22,
        _LBIns_T_43 ? LBIns_pb_IPIN_FF_21 : IPIN_21,
        _LBIns_T_41 ? LBIns_pb_IPIN_FF_20 : IPIN_20,
        _LBIns_T_39 ? LBIns_pb_IPIN_FF_19 : IPIN_19,
        _LBIns_T_37 ? LBIns_pb_IPIN_FF_18 : IPIN_18,
        _LBIns_T_35 ? LBIns_pb_IPIN_FF_17 : IPIN_17,
        _LBIns_T_33 ? LBIns_pb_IPIN_FF_16 : IPIN_16}),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:37:42, :40:86, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
    .c_out_mul (_custMul_c_out_mul)
  );
  assign OPIN_32 = _OPIN_32_T_2 ? OPIN_32_pb_OPIN_FF_0 : _custMul_c_out_mul[0];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_33 = _OPIN_33_T_2 ? OPIN_33_pb_OPIN_FF_1 : _custMul_c_out_mul[1];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_34 = _OPIN_34_T_2 ? OPIN_34_pb_OPIN_FF_2 : _custMul_c_out_mul[2];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_35 = _OPIN_35_T_2 ? OPIN_35_pb_OPIN_FF_3 : _custMul_c_out_mul[3];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_36 = _OPIN_36_T_2 ? OPIN_36_pb_OPIN_FF_4 : _custMul_c_out_mul[4];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_37 = _OPIN_37_T_2 ? OPIN_37_pb_OPIN_FF_5 : _custMul_c_out_mul[5];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_38 = _OPIN_38_T_2 ? OPIN_38_pb_OPIN_FF_6 : _custMul_c_out_mul[6];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_39 = _OPIN_39_T_2 ? OPIN_39_pb_OPIN_FF_7 : _custMul_c_out_mul[7];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_40 = _OPIN_40_T_2 ? OPIN_40_pb_OPIN_FF_8 : _custMul_c_out_mul[8];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_41 = _OPIN_41_T_2 ? OPIN_41_pb_OPIN_FF_9 : _custMul_c_out_mul[9];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_42 = _OPIN_42_T_2 ? OPIN_42_pb_OPIN_FF_10 : _custMul_c_out_mul[10];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_43 = _OPIN_43_T_2 ? OPIN_43_pb_OPIN_FF_11 : _custMul_c_out_mul[11];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_44 = _OPIN_44_T_2 ? OPIN_44_pb_OPIN_FF_12 : _custMul_c_out_mul[12];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_45 = _OPIN_45_T_2 ? OPIN_45_pb_OPIN_FF_13 : _custMul_c_out_mul[13];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_46 = _OPIN_46_T_2 ? OPIN_46_pb_OPIN_FF_14 : _custMul_c_out_mul[14];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_47 = _OPIN_47_T_2 ? OPIN_47_pb_OPIN_FF_15 : _custMul_c_out_mul[15];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CustMulBlock.scala:10:7, :43:23, :50:{39,59}, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
endmodule

