/* Generated by Yosys 0.33+34 (git sha1 b84ed5d3a, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_counter_test/inputs/counter.v:1.1-32.10" *)
module counter(IN, OUT, clk);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_counter_test/inputs/counter.v:3.19-3.21" *)
  input [127:0] IN;
  wire [127:0] IN;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_counter_test/inputs/counter.v:4.21-4.24" *)
  output [127:0] OUT;
  wire [127:0] OUT;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_counter_test/inputs/counter.v:5.11-5.14" *)
  input clk;
  wire clk;
  assign _00_ = 16'h1441 >> { OUT[34], IN[1], _04_, IN[0] };
  assign _04_ = 8'h17 >> { OUT[33:32], IN[1] };
  assign _01_ = 16'h4114 >> { OUT[33:32], IN[1:0] };
  assign _02_ = 4'h1 >> { OUT[32], IN[0] };
  assign _03_ = 8'h41 >> { OUT[35], _05_, IN[0] };
  assign _05_ = 16'hbffd >> { OUT[34:32], IN[1] };
  reg \OUT_reg[32] ;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_counter_test/inputs/counter.v:22.2-29.5" *)
  always @(posedge clk)
    \OUT_reg[32]  <= _02_;
  assign OUT[32] = \OUT_reg[32] ;
  reg \OUT_reg[33] ;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_counter_test/inputs/counter.v:22.2-29.5" *)
  always @(posedge clk)
    \OUT_reg[33]  <= _01_;
  assign OUT[33] = \OUT_reg[33] ;
  reg \OUT_reg[34] ;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_counter_test/inputs/counter.v:22.2-29.5" *)
  always @(posedge clk)
    \OUT_reg[34]  <= _00_;
  assign OUT[34] = \OUT_reg[34] ;
  reg \OUT_reg[35] ;
  (* src = "/home/kmgroup/projects/tutorial/fpga_cad_flow/example_designs/simple_fpga_counter_test/inputs/counter.v:22.2-29.5" *)
  always @(posedge clk)
    \OUT_reg[35]  <= _03_;
  assign OUT[35] = \OUT_reg[35] ;
  assign { OUT[127:36], OUT[31:0] } = 124'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
endmodule
