// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module AluAdd16(	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:109:7
  input  [15:0] io_i0,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:110:14
                io_i1,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:110:14
  input         io_cin,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:110:14
  input  [7:0]  io_ctrl,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:110:14
  output [15:0] io_q,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:110:14
  output        io_cout,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:110:14
  input  [31:0] io_config	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:110:14
);

  wire [16:0] _sum_T_4 =
    {1'h0, io_i0} + {1'h0, {16{io_config[0]}} ^ io_i1}
    + {16'h0, io_config[1] ? io_cin : io_ctrl[0]} + {16'h0, io_config[0]};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:125:{16,26}, :126:{20,30,50}, :127:{17,24,34}
  assign io_q = _sum_T_4[15:0];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:109:7, :127:34, :128:8
  assign io_cout = _sum_T_4[16];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:109:7, :127:34, :129:17
endmodule

// external module Mux16C

module Ble4(	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
  input         clock,	// <stdin>:122:11, :155:11, :188:11, :221:11, :254:11, :287:11, :320:11, :353:11
                reset,	// <stdin>:123:11, :156:11, :189:11, :222:11, :255:11, :288:11, :321:11, :354:11
  input  [19:0] io_config,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
  input         io_in_0,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
                io_in_1,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
                io_in_2,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
                io_in_3,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
  output        io_outR,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
                io_outT,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
  input         io_clkEnb,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
                io_loopBreak	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
);

  wire _lut_o;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:97:27
  reg  bleFF;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:101:32
  always @(posedge clock) begin	// <stdin>:122:11, :155:11, :188:11, :221:11, :254:11, :287:11, :320:11, :353:11
    if (reset)	// <stdin>:122:11, :155:11, :188:11, :221:11, :254:11, :287:11, :320:11, :353:11
      bleFF <= 1'h0;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7, :101:32
    else if (io_clkEnb) begin	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
    end
    else	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:87:14
      bleFF <= _lut_o;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:97:27, :101:32
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
      `FIRRTL_BEFORE_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
      automatic logic [31:0] _RANDOM[0:0];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
      `ifdef INIT_RANDOM_PROLOG_	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
        `INIT_RANDOM_PROLOG_	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
        bleFF = _RANDOM[/*Zero width*/ 1'b0][0];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7, :101:32
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
      `FIRRTL_AFTER_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Mux16C lut (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:97:27
    .in  (io_config[15:0]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:98:22
    .sel ({io_in_3, io_in_2, io_in_1, io_in_0}),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:99:20
    .o   (_lut_o)
  );
  assign io_outR = io_config[16] & ~io_loopBreak ? _lut_o : bleFF;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7, :97:27, :101:32, :104:{17,27,32,34}
  assign io_outT = io_config[17] & ~io_loopBreak ? _lut_o : bleFF;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:86:7, :97:27, :101:32, :104:34, :105:{17,27,32}
endmodule

module CLBlut4N10Alu(	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
  input          IPIN_0,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_1,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_2,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_3,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_4,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_5,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_6,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_7,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_8,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_9,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_10,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_11,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_12,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_13,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_14,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_15,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_16,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_17,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_18,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_19,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_20,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_21,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_22,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_23,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_24,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_25,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_26,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_27,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_28,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_29,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_30,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_31,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_32,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_33,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_34,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_35,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_36,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_37,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_38,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_39,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_40,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
                 IPIN_41,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:21:12
  output         OPIN_42,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_43,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_44,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_45,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_46,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_47,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_48,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_49,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_50,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_51,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_52,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_53,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_54,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_55,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_56,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_57,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
                 OPIN_58,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:24:12
  input          clock,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:26:33
                 reset,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:27:33
  input  [193:0] configBits,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:29:37
  input          loopBreak,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:30:36
                 gndLBouts,	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:31:36
                 pathBreak	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:32:36
);

  wire        OAlu_15;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_14;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_13;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_12;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_11;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_10;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_9;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_8;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_7;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_6;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_5;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_4;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_3;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_2;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_1;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        OAlu_0;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:56:50
  wire        _BLE_7_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_7_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_6_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_6_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_5_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_5_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_4_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_4_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_3_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_3_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_2_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_2_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_1_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_1_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_0_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire        _BLE_0_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
  wire [15:0] _alu_io_q;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53
  wire        _alu_io_cout;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53
  reg         LBIns_pb_IPIN_FF_0;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_1;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_2;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_3;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_4;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_5;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_6;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_7;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_8;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_9;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_10;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_11;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_12;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_13;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_14;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_15;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_16;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_17;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_18;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_19;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_20;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_21;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_22;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_23;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_24;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_25;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_26;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_27;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_28;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_29;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_30;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_31;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_32;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_33;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_34;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_35;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_36;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_37;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_38;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_39;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_40;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  reg         LBIns_pb_IPIN_FF_41;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux = (configBits[192] ? OAlu_0 : _BLE_0_io_outR) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_42_pb_OPIN_FF_0;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_1 = (configBits[192] ? OAlu_1 : _BLE_1_io_outR) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_43_pb_OPIN_FF_1;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_2 = (configBits[192] ? OAlu_2 : _BLE_2_io_outR) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_44_pb_OPIN_FF_2;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_3 = (configBits[192] ? OAlu_3 : _BLE_3_io_outR) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_45_pb_OPIN_FF_3;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_4 = (configBits[192] ? OAlu_4 : _BLE_4_io_outR) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_46_pb_OPIN_FF_4;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_5 = (configBits[192] ? OAlu_5 : _BLE_5_io_outR) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_47_pb_OPIN_FF_5;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_6 = (configBits[192] ? OAlu_6 : _BLE_6_io_outR) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_48_pb_OPIN_FF_6;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_7 = (configBits[192] ? OAlu_7 : _BLE_7_io_outR) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_49_pb_OPIN_FF_7;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_8 = (configBits[192] ? OAlu_8 : _BLE_0_io_outT) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_50_pb_OPIN_FF_8;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_9 = (configBits[192] ? OAlu_9 : _BLE_1_io_outT) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_51_pb_OPIN_FF_9;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_10 = (configBits[192] ? OAlu_10 : _BLE_2_io_outT) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_52_pb_OPIN_FF_10;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_11 = (configBits[192] ? OAlu_11 : _BLE_3_io_outT) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_53_pb_OPIN_FF_11;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_12 = (configBits[192] ? OAlu_12 : _BLE_4_io_outT) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_54_pb_OPIN_FF_12;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_13 = (configBits[192] ? OAlu_13 : _BLE_5_io_outT) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_55_pb_OPIN_FF_13;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_14 = (configBits[192] ? OAlu_14 : _BLE_6_io_outT) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_56_pb_OPIN_FF_14;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_15 = (configBits[192] ? OAlu_15 : _BLE_7_io_outT) & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{24,35,76,78}, :56:50, :64:48
  reg         OPIN_57_pb_OPIN_FF_15;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  wire        aluClbMux_16 = configBits[192] & _alu_io_cout & ~gndLBouts;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:{35,76,78}, :51:53
  reg         OPIN_58_pb_OPIN_FF_16;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
  assign OAlu_0 = _alu_io_q[0];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_1 = _alu_io_q[1];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_2 = _alu_io_q[2];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_3 = _alu_io_q[3];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_4 = _alu_io_q[4];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_5 = _alu_io_q[5];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_6 = _alu_io_q[6];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_7 = _alu_io_q[7];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_8 = _alu_io_q[8];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_9 = _alu_io_q[9];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_10 = _alu_io_q[10];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_11 = _alu_io_q[11];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_12 = _alu_io_q[12];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_13 = _alu_io_q[13];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_14 = _alu_io_q[14];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  assign OAlu_15 = _alu_io_q[15];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53, :56:50
  wire [3:0]  _GEN =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_3},
         {LBIns_pb_IPIN_FF_2},
         {LBIns_pb_IPIN_FF_1},
         {LBIns_pb_IPIN_FF_0}}
      : {{IPIN_3}, {IPIN_2}, {IPIN_1}, {IPIN_0}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_0 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_11},
         {LBIns_pb_IPIN_FF_10},
         {LBIns_pb_IPIN_FF_9},
         {LBIns_pb_IPIN_FF_8}}
      : {{IPIN_11}, {IPIN_10}, {IPIN_9}, {IPIN_8}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_1 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_19},
         {LBIns_pb_IPIN_FF_18},
         {LBIns_pb_IPIN_FF_17},
         {LBIns_pb_IPIN_FF_16}}
      : {{IPIN_19}, {IPIN_18}, {IPIN_17}, {IPIN_16}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_2 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_27},
         {LBIns_pb_IPIN_FF_26},
         {LBIns_pb_IPIN_FF_25},
         {LBIns_pb_IPIN_FF_24}}
      : {{IPIN_27}, {IPIN_26}, {IPIN_25}, {IPIN_24}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_3 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_4},
         {LBIns_pb_IPIN_FF_3},
         {LBIns_pb_IPIN_FF_2},
         {LBIns_pb_IPIN_FF_1}}
      : {{IPIN_4}, {IPIN_3}, {IPIN_2}, {IPIN_1}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_4 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_12},
         {LBIns_pb_IPIN_FF_11},
         {LBIns_pb_IPIN_FF_10},
         {LBIns_pb_IPIN_FF_9}}
      : {{IPIN_12}, {IPIN_11}, {IPIN_10}, {IPIN_9}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_5 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_20},
         {LBIns_pb_IPIN_FF_19},
         {LBIns_pb_IPIN_FF_18},
         {LBIns_pb_IPIN_FF_17}}
      : {{IPIN_20}, {IPIN_19}, {IPIN_18}, {IPIN_17}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_6 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_28},
         {LBIns_pb_IPIN_FF_27},
         {LBIns_pb_IPIN_FF_26},
         {LBIns_pb_IPIN_FF_25}}
      : {{IPIN_28}, {IPIN_27}, {IPIN_26}, {IPIN_25}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_7 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_5},
         {LBIns_pb_IPIN_FF_4},
         {LBIns_pb_IPIN_FF_3},
         {LBIns_pb_IPIN_FF_2}}
      : {{IPIN_5}, {IPIN_4}, {IPIN_3}, {IPIN_2}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_8 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_13},
         {LBIns_pb_IPIN_FF_12},
         {LBIns_pb_IPIN_FF_11},
         {LBIns_pb_IPIN_FF_10}}
      : {{IPIN_13}, {IPIN_12}, {IPIN_11}, {IPIN_10}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_9 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_21},
         {LBIns_pb_IPIN_FF_20},
         {LBIns_pb_IPIN_FF_19},
         {LBIns_pb_IPIN_FF_18}}
      : {{IPIN_21}, {IPIN_20}, {IPIN_19}, {IPIN_18}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_10 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_29},
         {LBIns_pb_IPIN_FF_28},
         {LBIns_pb_IPIN_FF_27},
         {LBIns_pb_IPIN_FF_26}}
      : {{IPIN_29}, {IPIN_28}, {IPIN_27}, {IPIN_26}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_11 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_6},
         {LBIns_pb_IPIN_FF_5},
         {LBIns_pb_IPIN_FF_4},
         {LBIns_pb_IPIN_FF_3}}
      : {{IPIN_6}, {IPIN_5}, {IPIN_4}, {IPIN_3}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_12 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_14},
         {LBIns_pb_IPIN_FF_13},
         {LBIns_pb_IPIN_FF_12},
         {LBIns_pb_IPIN_FF_11}}
      : {{IPIN_14}, {IPIN_13}, {IPIN_12}, {IPIN_11}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_13 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_22},
         {LBIns_pb_IPIN_FF_21},
         {LBIns_pb_IPIN_FF_20},
         {LBIns_pb_IPIN_FF_19}}
      : {{IPIN_22}, {IPIN_21}, {IPIN_20}, {IPIN_19}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_14 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_30},
         {LBIns_pb_IPIN_FF_29},
         {LBIns_pb_IPIN_FF_28},
         {LBIns_pb_IPIN_FF_27}}
      : {{IPIN_30}, {IPIN_29}, {IPIN_28}, {IPIN_27}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_15 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_7},
         {LBIns_pb_IPIN_FF_6},
         {LBIns_pb_IPIN_FF_5},
         {LBIns_pb_IPIN_FF_4}}
      : {{IPIN_7}, {IPIN_6}, {IPIN_5}, {IPIN_4}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_16 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_15},
         {LBIns_pb_IPIN_FF_14},
         {LBIns_pb_IPIN_FF_13},
         {LBIns_pb_IPIN_FF_12}}
      : {{IPIN_15}, {IPIN_14}, {IPIN_13}, {IPIN_12}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_17 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_23},
         {LBIns_pb_IPIN_FF_22},
         {LBIns_pb_IPIN_FF_21},
         {LBIns_pb_IPIN_FF_20}}
      : {{IPIN_23}, {IPIN_22}, {IPIN_21}, {IPIN_20}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_18 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_31},
         {LBIns_pb_IPIN_FF_30},
         {LBIns_pb_IPIN_FF_29},
         {LBIns_pb_IPIN_FF_28}}
      : {{IPIN_31}, {IPIN_30}, {IPIN_29}, {IPIN_28}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_19 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_0},
         {LBIns_pb_IPIN_FF_7},
         {LBIns_pb_IPIN_FF_6},
         {LBIns_pb_IPIN_FF_5}}
      : {{IPIN_0}, {IPIN_7}, {IPIN_6}, {IPIN_5}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_20 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_8},
         {LBIns_pb_IPIN_FF_15},
         {LBIns_pb_IPIN_FF_14},
         {LBIns_pb_IPIN_FF_13}}
      : {{IPIN_8}, {IPIN_15}, {IPIN_14}, {IPIN_13}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_21 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_16},
         {LBIns_pb_IPIN_FF_23},
         {LBIns_pb_IPIN_FF_22},
         {LBIns_pb_IPIN_FF_21}}
      : {{IPIN_16}, {IPIN_23}, {IPIN_22}, {IPIN_21}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_22 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_24},
         {LBIns_pb_IPIN_FF_31},
         {LBIns_pb_IPIN_FF_30},
         {LBIns_pb_IPIN_FF_29}}
      : {{IPIN_24}, {IPIN_31}, {IPIN_30}, {IPIN_29}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_23 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_1},
         {LBIns_pb_IPIN_FF_0},
         {LBIns_pb_IPIN_FF_7},
         {LBIns_pb_IPIN_FF_6}}
      : {{IPIN_1}, {IPIN_0}, {IPIN_7}, {IPIN_6}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_24 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_9},
         {LBIns_pb_IPIN_FF_8},
         {LBIns_pb_IPIN_FF_15},
         {LBIns_pb_IPIN_FF_14}}
      : {{IPIN_9}, {IPIN_8}, {IPIN_15}, {IPIN_14}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_25 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_17},
         {LBIns_pb_IPIN_FF_16},
         {LBIns_pb_IPIN_FF_23},
         {LBIns_pb_IPIN_FF_22}}
      : {{IPIN_17}, {IPIN_16}, {IPIN_23}, {IPIN_22}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_26 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_25},
         {LBIns_pb_IPIN_FF_24},
         {LBIns_pb_IPIN_FF_31},
         {LBIns_pb_IPIN_FF_30}}
      : {{IPIN_25}, {IPIN_24}, {IPIN_31}, {IPIN_30}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_27 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_2},
         {LBIns_pb_IPIN_FF_1},
         {LBIns_pb_IPIN_FF_0},
         {LBIns_pb_IPIN_FF_7}}
      : {{IPIN_2}, {IPIN_1}, {IPIN_0}, {IPIN_7}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_28 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_10},
         {LBIns_pb_IPIN_FF_9},
         {LBIns_pb_IPIN_FF_8},
         {LBIns_pb_IPIN_FF_15}}
      : {{IPIN_10}, {IPIN_9}, {IPIN_8}, {IPIN_15}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_29 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_18},
         {LBIns_pb_IPIN_FF_17},
         {LBIns_pb_IPIN_FF_16},
         {LBIns_pb_IPIN_FF_23}}
      : {{IPIN_18}, {IPIN_17}, {IPIN_16}, {IPIN_23}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  wire [3:0]  _GEN_30 =
    pathBreak
      ? {{LBIns_pb_IPIN_FF_26},
         {LBIns_pb_IPIN_FF_25},
         {LBIns_pb_IPIN_FF_24},
         {LBIns_pb_IPIN_FF_31}}
      : {{IPIN_26}, {IPIN_25}, {IPIN_24}, {IPIN_31}};	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:122, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  always @(posedge clock) begin	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:26:33
    if (pathBreak) begin	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:32:36
      LBIns_pb_IPIN_FF_0 <= IPIN_0;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_1 <= IPIN_1;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_2 <= IPIN_2;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_3 <= IPIN_3;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_4 <= IPIN_4;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_5 <= IPIN_5;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_6 <= IPIN_6;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_7 <= IPIN_7;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_8 <= IPIN_8;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_9 <= IPIN_9;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_10 <= IPIN_10;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_11 <= IPIN_11;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_12 <= IPIN_12;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_13 <= IPIN_13;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_14 <= IPIN_14;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_15 <= IPIN_15;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_16 <= IPIN_16;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_17 <= IPIN_17;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_18 <= IPIN_18;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_19 <= IPIN_19;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_20 <= IPIN_20;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_21 <= IPIN_21;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_22 <= IPIN_22;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_23 <= IPIN_23;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_24 <= IPIN_24;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_25 <= IPIN_25;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_26 <= IPIN_26;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_27 <= IPIN_27;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_28 <= IPIN_28;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_29 <= IPIN_29;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_30 <= IPIN_30;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_31 <= IPIN_31;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_32 <= IPIN_32;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_33 <= IPIN_33;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_34 <= IPIN_34;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_35 <= IPIN_35;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_36 <= IPIN_36;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_37 <= IPIN_37;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_38 <= IPIN_38;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_39 <= IPIN_39;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_40 <= IPIN_40;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      LBIns_pb_IPIN_FF_41 <= IPIN_41;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_42_pb_OPIN_FF_0 <= aluClbMux;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_43_pb_OPIN_FF_1 <= aluClbMux_1;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_44_pb_OPIN_FF_2 <= aluClbMux_2;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_45_pb_OPIN_FF_3 <= aluClbMux_3;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_46_pb_OPIN_FF_4 <= aluClbMux_4;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_47_pb_OPIN_FF_5 <= aluClbMux_5;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_48_pb_OPIN_FF_6 <= aluClbMux_6;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_49_pb_OPIN_FF_7 <= aluClbMux_7;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_50_pb_OPIN_FF_8 <= aluClbMux_8;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_51_pb_OPIN_FF_9 <= aluClbMux_9;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_52_pb_OPIN_FF_10 <= aluClbMux_10;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_53_pb_OPIN_FF_11 <= aluClbMux_11;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_54_pb_OPIN_FF_12 <= aluClbMux_12;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_55_pb_OPIN_FF_13 <= aluClbMux_13;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_56_pb_OPIN_FF_14 <= aluClbMux_14;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_57_pb_OPIN_FF_15 <= aluClbMux_15;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      OPIN_58_pb_OPIN_FF_16 <= aluClbMux_16;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
      `FIRRTL_BEFORE_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
      automatic logic [31:0] _RANDOM[0:1];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
      `ifdef INIT_RANDOM_PROLOG_	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
        `INIT_RANDOM_PROLOG_	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
        end	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
        LBIns_pb_IPIN_FF_0 = _RANDOM[1'h0][0];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_1 = _RANDOM[1'h0][1];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_2 = _RANDOM[1'h0][2];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_3 = _RANDOM[1'h0][3];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_4 = _RANDOM[1'h0][4];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_5 = _RANDOM[1'h0][5];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_6 = _RANDOM[1'h0][6];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_7 = _RANDOM[1'h0][7];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_8 = _RANDOM[1'h0][8];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_9 = _RANDOM[1'h0][9];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_10 = _RANDOM[1'h0][10];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_11 = _RANDOM[1'h0][11];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_12 = _RANDOM[1'h0][12];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_13 = _RANDOM[1'h0][13];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_14 = _RANDOM[1'h0][14];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_15 = _RANDOM[1'h0][15];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_16 = _RANDOM[1'h0][16];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_17 = _RANDOM[1'h0][17];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_18 = _RANDOM[1'h0][18];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_19 = _RANDOM[1'h0][19];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_20 = _RANDOM[1'h0][20];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_21 = _RANDOM[1'h0][21];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_22 = _RANDOM[1'h0][22];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_23 = _RANDOM[1'h0][23];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_24 = _RANDOM[1'h0][24];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_25 = _RANDOM[1'h0][25];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_26 = _RANDOM[1'h0][26];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_27 = _RANDOM[1'h0][27];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_28 = _RANDOM[1'h0][28];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_29 = _RANDOM[1'h0][29];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_30 = _RANDOM[1'h0][30];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_31 = _RANDOM[1'h0][31];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_32 = _RANDOM[1'h1][0];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_33 = _RANDOM[1'h1][1];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_34 = _RANDOM[1'h1][2];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_35 = _RANDOM[1'h1][3];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_36 = _RANDOM[1'h1][4];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_37 = _RANDOM[1'h1][5];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_38 = _RANDOM[1'h1][6];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_39 = _RANDOM[1'h1][7];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_40 = _RANDOM[1'h1][8];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        LBIns_pb_IPIN_FF_41 = _RANDOM[1'h1][9];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_42_pb_OPIN_FF_0 = _RANDOM[1'h1][10];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_43_pb_OPIN_FF_1 = _RANDOM[1'h1][11];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_44_pb_OPIN_FF_2 = _RANDOM[1'h1][12];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_45_pb_OPIN_FF_3 = _RANDOM[1'h1][13];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_46_pb_OPIN_FF_4 = _RANDOM[1'h1][14];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_47_pb_OPIN_FF_5 = _RANDOM[1'h1][15];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_48_pb_OPIN_FF_6 = _RANDOM[1'h1][16];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_49_pb_OPIN_FF_7 = _RANDOM[1'h1][17];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_50_pb_OPIN_FF_8 = _RANDOM[1'h1][18];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_51_pb_OPIN_FF_9 = _RANDOM[1'h1][19];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_52_pb_OPIN_FF_10 = _RANDOM[1'h1][20];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_53_pb_OPIN_FF_11 = _RANDOM[1'h1][21];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_54_pb_OPIN_FF_12 = _RANDOM[1'h1][22];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_55_pb_OPIN_FF_13 = _RANDOM[1'h1][23];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_56_pb_OPIN_FF_14 = _RANDOM[1'h1][24];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_57_pb_OPIN_FF_15 = _RANDOM[1'h1][25];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
        OPIN_58_pb_OPIN_FF_16 = _RANDOM[1'h1][26];	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
      `FIRRTL_AFTER_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  AluAdd16 alu (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:51:53
    .io_i0
      ({pathBreak ? LBIns_pb_IPIN_FF_15 : IPIN_15,
        pathBreak ? LBIns_pb_IPIN_FF_14 : IPIN_14,
        pathBreak ? LBIns_pb_IPIN_FF_13 : IPIN_13,
        pathBreak ? LBIns_pb_IPIN_FF_12 : IPIN_12,
        pathBreak ? LBIns_pb_IPIN_FF_11 : IPIN_11,
        pathBreak ? LBIns_pb_IPIN_FF_10 : IPIN_10,
        pathBreak ? LBIns_pb_IPIN_FF_9 : IPIN_9,
        pathBreak ? LBIns_pb_IPIN_FF_8 : IPIN_8,
        pathBreak ? LBIns_pb_IPIN_FF_7 : IPIN_7,
        pathBreak ? LBIns_pb_IPIN_FF_6 : IPIN_6,
        pathBreak ? LBIns_pb_IPIN_FF_5 : IPIN_5,
        pathBreak ? LBIns_pb_IPIN_FF_4 : IPIN_4,
        pathBreak ? LBIns_pb_IPIN_FF_3 : IPIN_3,
        pathBreak ? LBIns_pb_IPIN_FF_2 : IPIN_2,
        pathBreak ? LBIns_pb_IPIN_FF_1 : IPIN_1,
        pathBreak ? LBIns_pb_IPIN_FF_0 : IPIN_0}),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:52:27, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
    .io_i1
      ({pathBreak ? LBIns_pb_IPIN_FF_31 : IPIN_31,
        pathBreak ? LBIns_pb_IPIN_FF_30 : IPIN_30,
        pathBreak ? LBIns_pb_IPIN_FF_29 : IPIN_29,
        pathBreak ? LBIns_pb_IPIN_FF_28 : IPIN_28,
        pathBreak ? LBIns_pb_IPIN_FF_27 : IPIN_27,
        pathBreak ? LBIns_pb_IPIN_FF_26 : IPIN_26,
        pathBreak ? LBIns_pb_IPIN_FF_25 : IPIN_25,
        pathBreak ? LBIns_pb_IPIN_FF_24 : IPIN_24,
        pathBreak ? LBIns_pb_IPIN_FF_23 : IPIN_23,
        pathBreak ? LBIns_pb_IPIN_FF_22 : IPIN_22,
        pathBreak ? LBIns_pb_IPIN_FF_21 : IPIN_21,
        pathBreak ? LBIns_pb_IPIN_FF_20 : IPIN_20,
        pathBreak ? LBIns_pb_IPIN_FF_19 : IPIN_19,
        pathBreak ? LBIns_pb_IPIN_FF_18 : IPIN_18,
        pathBreak ? LBIns_pb_IPIN_FF_17 : IPIN_17,
        pathBreak ? LBIns_pb_IPIN_FF_16 : IPIN_16}),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:53:27, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
    .io_cin    (pathBreak ? LBIns_pb_IPIN_FF_40 : IPIN_40),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
    .io_ctrl
      ({pathBreak ? LBIns_pb_IPIN_FF_39 : IPIN_39,
        pathBreak ? LBIns_pb_IPIN_FF_38 : IPIN_38,
        pathBreak ? LBIns_pb_IPIN_FF_37 : IPIN_37,
        pathBreak ? LBIns_pb_IPIN_FF_36 : IPIN_36,
        pathBreak ? LBIns_pb_IPIN_FF_35 : IPIN_35,
        pathBreak ? LBIns_pb_IPIN_FF_34 : IPIN_34,
        pathBreak ? LBIns_pb_IPIN_FF_33 : IPIN_33,
        pathBreak ? LBIns_pb_IPIN_FF_32 : IPIN_32}),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:54:29, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
    .io_q      (_alu_io_q),
    .io_cout   (_alu_io_cout),
    .io_config (configBits[191:160])	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:59:30
  );
  Ble4 BLE_0 (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[19:0]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:68:38
    .io_in_0      (_GEN[configBits[19:18]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_1      (_GEN_0[configBits[19:18]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_2      (_GEN_1[configBits[19:18]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_3      (_GEN_2[configBits[19:18]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_outR      (_BLE_0_io_outR),
    .io_outT      (_BLE_0_io_outT),
    .io_clkEnb    (configBits[193]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:58:30
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_1 (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[39:20]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:68:38
    .io_in_0      (_GEN_3[configBits[39:38]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_1      (_GEN_4[configBits[39:38]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_2      (_GEN_5[configBits[39:38]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_3      (_GEN_6[configBits[39:38]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_outR      (_BLE_1_io_outR),
    .io_outT      (_BLE_1_io_outT),
    .io_clkEnb    (configBits[193]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:58:30
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_2 (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[59:40]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:68:38
    .io_in_0      (_GEN_7[configBits[59:58]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_1      (_GEN_8[configBits[59:58]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_2      (_GEN_9[configBits[59:58]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_3      (_GEN_10[configBits[59:58]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_outR      (_BLE_2_io_outR),
    .io_outT      (_BLE_2_io_outT),
    .io_clkEnb    (configBits[193]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:58:30
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_3 (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[79:60]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:68:38
    .io_in_0      (_GEN_11[configBits[79:78]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_1      (_GEN_12[configBits[79:78]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_2      (_GEN_13[configBits[79:78]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_3      (_GEN_14[configBits[79:78]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_outR      (_BLE_3_io_outR),
    .io_outT      (_BLE_3_io_outT),
    .io_clkEnb    (configBits[193]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:58:30
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_4 (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[99:80]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:68:38
    .io_in_0      (_GEN_15[configBits[99:98]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_1      (_GEN_16[configBits[99:98]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_2      (_GEN_17[configBits[99:98]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_3      (_GEN_18[configBits[99:98]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_outR      (_BLE_4_io_outR),
    .io_outT      (_BLE_4_io_outT),
    .io_clkEnb    (configBits[193]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:58:30
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_5 (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[119:100]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:68:38
    .io_in_0      (_GEN_19[configBits[119:118]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_1      (_GEN_20[configBits[119:118]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_2      (_GEN_21[configBits[119:118]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_3      (_GEN_22[configBits[119:118]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_outR      (_BLE_5_io_outR),
    .io_outT      (_BLE_5_io_outT),
    .io_clkEnb    (configBits[193]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:58:30
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_6 (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[139:120]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:68:38
    .io_in_0      (_GEN_23[configBits[139:138]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_1      (_GEN_24[configBits[139:138]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_2      (_GEN_25[configBits[139:138]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_3      (_GEN_26[configBits[139:138]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_outR      (_BLE_6_io_outR),
    .io_outT      (_BLE_6_io_outT),
    .io_clkEnb    (configBits[193]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:58:30
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_7 (	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:64:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[159:140]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:68:38
    .io_in_0      (_GEN_27[configBits[159:158]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_1      (_GEN_28[configBits[159:158]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_2      (_GEN_29[configBits[159:158]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_in_3      (_GEN_30[configBits[159:158]]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:69:{69,122}
    .io_outR      (_BLE_7_io_outR),
    .io_outT      (_BLE_7_io_outT),
    .io_clkEnb    (configBits[193]),	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:58:30
    .io_loopBreak (loopBreak)
  );
  assign OPIN_42 = pathBreak ? OPIN_42_pb_OPIN_FF_0 : aluClbMux;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_43 = pathBreak ? OPIN_43_pb_OPIN_FF_1 : aluClbMux_1;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_44 = pathBreak ? OPIN_44_pb_OPIN_FF_2 : aluClbMux_2;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_45 = pathBreak ? OPIN_45_pb_OPIN_FF_3 : aluClbMux_3;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_46 = pathBreak ? OPIN_46_pb_OPIN_FF_4 : aluClbMux_4;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_47 = pathBreak ? OPIN_47_pb_OPIN_FF_5 : aluClbMux_5;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_48 = pathBreak ? OPIN_48_pb_OPIN_FF_6 : aluClbMux_6;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_49 = pathBreak ? OPIN_49_pb_OPIN_FF_7 : aluClbMux_7;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_50 = pathBreak ? OPIN_50_pb_OPIN_FF_8 : aluClbMux_8;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_51 = pathBreak ? OPIN_51_pb_OPIN_FF_9 : aluClbMux_9;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_52 = pathBreak ? OPIN_52_pb_OPIN_FF_10 : aluClbMux_10;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_53 = pathBreak ? OPIN_53_pb_OPIN_FF_11 : aluClbMux_11;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_54 = pathBreak ? OPIN_54_pb_OPIN_FF_12 : aluClbMux_12;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_55 = pathBreak ? OPIN_55_pb_OPIN_FF_13 : aluClbMux_13;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_56 = pathBreak ? OPIN_56_pb_OPIN_FF_14 : aluClbMux_14;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_57 = pathBreak ? OPIN_57_pb_OPIN_FF_15 : aluClbMux_15;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
  assign OPIN_58 = pathBreak ? OPIN_58_pb_OPIN_FF_16 : aluClbMux_16;	// home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/logicblks/CLBlut4N10Alu.scala:11:7, :46:76, home/kmgroup/projects/tutorial/efpga_basic_asap7/src/main/scala/efpga/utils/MuxCE.scala:55:25, :56:8
endmodule

