// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// external module Mux16C

module Ble4(	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
  input         clock,	// <stdin>:96:11, :133:11, :170:11, :207:11, :244:11, :281:11, :318:11, :355:11
                reset,	// <stdin>:97:11, :134:11, :171:11, :208:11, :245:11, :282:11, :319:11, :356:11
  input  [19:0] io_config,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
  input         io_in_0,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
                io_in_1,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
                io_in_2,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
                io_in_3,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
  output        io_outR,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
                io_outT,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
  input         io_gndOuts,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
                io_clkEnb,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
                io_loopBreak	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
);

  wire _lut_o;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:76:27
  reg  bleFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:80:32
  always @(posedge clock) begin	// <stdin>:96:11, :133:11, :170:11, :207:11, :244:11, :281:11, :318:11, :355:11
    if (reset)	// <stdin>:96:11, :133:11, :170:11, :207:11, :244:11, :281:11, :318:11, :355:11
      bleFF <= 1'h0;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7, :80:32
    else if (io_clkEnb) begin	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
    end
    else	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:66:14
      bleFF <= _lut_o;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:76:27, :80:32
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
      `FIRRTL_BEFORE_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
      automatic logic [31:0] _RANDOM[0:0];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
      `ifdef INIT_RANDOM_PROLOG_	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
        `INIT_RANDOM_PROLOG_	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
        bleFF = _RANDOM[/*Zero width*/ 1'b0][0];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7, :80:32
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
      `FIRRTL_AFTER_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Mux16C lut (	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:76:27
    .in  (io_config[15:0]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:77:25
    .sel ({io_in_3, io_in_2, io_in_1, io_in_0}),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:78:23
    .o   (_lut_o)
  );
  assign io_outR = (io_config[16] & ~io_loopBreak ? _lut_o : bleFF) & ~io_gndOuts;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7, :76:27, :80:32, :83:{17,27,32,34,66,68}
  assign io_outT = (io_config[17] & ~io_loopBreak ? _lut_o : bleFF) & ~io_gndOuts;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Clb.scala:65:7, :76:27, :80:32, :83:{34,68}, :84:{17,27,32,66}
endmodule

module CLBlut4N10Mem(	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
  input          IPIN_0,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_1,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_2,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_3,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_4,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_5,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_6,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_7,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_8,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_9,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_10,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_11,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_12,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_13,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_14,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_15,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_16,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_17,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_18,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_19,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_20,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_21,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_22,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_23,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_24,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_25,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_26,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_27,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_28,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_29,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_30,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_31,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_32,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_33,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_34,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_35,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_36,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_37,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_38,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
                 IPIN_39,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:21:12
  output         OPIN_41,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_42,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_43,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_44,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_45,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_46,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_47,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_48,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_49,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_50,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_51,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_52,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_53,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_54,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_55,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
                 OPIN_56,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:24:12
  input          clock,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:26:33
                 reset,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:27:33
  input  [15:0]  ioPad_i,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:28:47
  output [39:0]  ioPad_o,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:28:47
  input  [162:0] configBits,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:29:37
  input          loopBreak,	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:30:36
                 gndLBouts	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:31:36
);

  wire        OMem_15;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_14;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_13;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_12;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_11;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_10;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_9;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_8;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_7;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_6;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_5;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_4;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_3;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_2;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_1;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        OMem_0;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:57
  wire        _BLE_7_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_7_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_6_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_6_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_5_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_5_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_4_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_4_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_3_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_3_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_2_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_2_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_1_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_1_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_0_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  wire        _BLE_0_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
  reg  [39:0] braminFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:45:42
  reg         OMem_0_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_0 = configBits[160] ? ioPad_i[0] : OMem_0_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_1_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_1 = configBits[160] ? ioPad_i[1] : OMem_1_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_2_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_2 = configBits[160] ? ioPad_i[2] : OMem_2_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_3_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_3 = configBits[160] ? ioPad_i[3] : OMem_3_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_4_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_4 = configBits[160] ? ioPad_i[4] : OMem_4_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_5_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_5 = configBits[160] ? ioPad_i[5] : OMem_5_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_6_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_6 = configBits[160] ? ioPad_i[6] : OMem_6_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_7_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_7 = configBits[160] ? ioPad_i[7] : OMem_7_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_8_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_8 = configBits[160] ? ioPad_i[8] : OMem_8_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_9_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_9 = configBits[160] ? ioPad_i[9] : OMem_9_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_10_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_10 = configBits[160] ? ioPad_i[10] : OMem_10_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_11_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_11 = configBits[160] ? ioPad_i[11] : OMem_11_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_12_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_12 = configBits[160] ? ioPad_i[12] : OMem_12_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_13_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_13 = configBits[160] ? ioPad_i[13] : OMem_13_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_14_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_14 = configBits[160] ? ioPad_i[14] : OMem_14_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  reg         OMem_15_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:132
  assign OMem_15 = configBits[160] ? ioPad_i[15] : OMem_15_bramoutFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:46:32, :48:{57,101,132}
  always @(posedge clock) begin	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:26:33
    braminFF <=
      {IPIN_39,
       IPIN_38,
       IPIN_37,
       IPIN_36,
       IPIN_35,
       IPIN_34,
       IPIN_33,
       IPIN_32,
       IPIN_31,
       IPIN_30,
       IPIN_29,
       IPIN_28,
       IPIN_27,
       IPIN_26,
       IPIN_25,
       IPIN_24,
       IPIN_23,
       IPIN_22,
       IPIN_21,
       IPIN_20,
       IPIN_19,
       IPIN_18,
       IPIN_17,
       IPIN_16,
       IPIN_15,
       IPIN_14,
       IPIN_13,
       IPIN_12,
       IPIN_11,
       IPIN_10,
       IPIN_9,
       IPIN_8,
       IPIN_7,
       IPIN_6,
       IPIN_5,
       IPIN_4,
       IPIN_3,
       IPIN_2,
       IPIN_1,
       IPIN_0};	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:45:{42,46}
    OMem_0_bramoutFF <= ioPad_i[0];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_1_bramoutFF <= ioPad_i[1];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_2_bramoutFF <= ioPad_i[2];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_3_bramoutFF <= ioPad_i[3];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_4_bramoutFF <= ioPad_i[4];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_5_bramoutFF <= ioPad_i[5];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_6_bramoutFF <= ioPad_i[6];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_7_bramoutFF <= ioPad_i[7];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_8_bramoutFF <= ioPad_i[8];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_9_bramoutFF <= ioPad_i[9];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_10_bramoutFF <= ioPad_i[10];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_11_bramoutFF <= ioPad_i[11];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_12_bramoutFF <= ioPad_i[12];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_13_bramoutFF <= ioPad_i[13];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_14_bramoutFF <= ioPad_i[14];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
    OMem_15_bramoutFF <= ioPad_i[15];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:48:{101,132}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
      `FIRRTL_BEFORE_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
      automatic logic [31:0] _RANDOM[0:1];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
      `ifdef INIT_RANDOM_PROLOG_	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
        `INIT_RANDOM_PROLOG_	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
        end	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
        braminFF = {_RANDOM[1'h0], _RANDOM[1'h1][7:0]};	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42
        OMem_0_bramoutFF = _RANDOM[1'h1][8];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_1_bramoutFF = _RANDOM[1'h1][9];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_2_bramoutFF = _RANDOM[1'h1][10];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_3_bramoutFF = _RANDOM[1'h1][11];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_4_bramoutFF = _RANDOM[1'h1][12];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_5_bramoutFF = _RANDOM[1'h1][13];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_6_bramoutFF = _RANDOM[1'h1][14];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_7_bramoutFF = _RANDOM[1'h1][15];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_8_bramoutFF = _RANDOM[1'h1][16];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_9_bramoutFF = _RANDOM[1'h1][17];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_10_bramoutFF = _RANDOM[1'h1][18];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_11_bramoutFF = _RANDOM[1'h1][19];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_12_bramoutFF = _RANDOM[1'h1][20];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_13_bramoutFF = _RANDOM[1'h1][21];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_14_bramoutFF = _RANDOM[1'h1][22];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
        OMem_15_bramoutFF = _RANDOM[1'h1][23];	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :48:132
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
      `FIRRTL_AFTER_INITIAL	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Ble4 BLE_0 (	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[19:0]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:57:38
    .io_in_0
      (configBits[19:18] == 2'h0 ? IPIN_0 : configBits[19:18] == 2'h1 ? IPIN_1 : IPIN_2),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_1
      (configBits[19:18] == 2'h0 ? IPIN_8 : configBits[19:18] == 2'h1 ? IPIN_9 : IPIN_10),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_2
      (configBits[19:18] == 2'h0
         ? IPIN_16
         : configBits[19:18] == 2'h1 ? IPIN_17 : IPIN_18),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_3
      (configBits[19:18] == 2'h0
         ? IPIN_24
         : configBits[19:18] == 2'h1 ? IPIN_25 : IPIN_26),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_outR      (_BLE_0_io_outR),
    .io_outT      (_BLE_0_io_outT),
    .io_gndOuts   (gndLBouts),
    .io_clkEnb    (configBits[162]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:63:38
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_1 (	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[39:20]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:57:38
    .io_in_0
      (configBits[19:18] == 2'h0 ? IPIN_1 : configBits[19:18] == 2'h1 ? IPIN_2 : IPIN_3),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_1
      (configBits[19:18] == 2'h0
         ? IPIN_9
         : configBits[19:18] == 2'h1 ? IPIN_10 : IPIN_11),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_2
      (configBits[19:18] == 2'h0
         ? IPIN_17
         : configBits[19:18] == 2'h1 ? IPIN_18 : IPIN_19),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_3
      (configBits[19:18] == 2'h0
         ? IPIN_25
         : configBits[19:18] == 2'h1 ? IPIN_26 : IPIN_27),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_outR      (_BLE_1_io_outR),
    .io_outT      (_BLE_1_io_outT),
    .io_gndOuts   (gndLBouts),
    .io_clkEnb    (configBits[162]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:63:38
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_2 (	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[59:40]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:57:38
    .io_in_0
      (configBits[19:18] == 2'h0 ? IPIN_2 : configBits[19:18] == 2'h1 ? IPIN_3 : IPIN_4),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_1
      (configBits[19:18] == 2'h0
         ? IPIN_10
         : configBits[19:18] == 2'h1 ? IPIN_11 : IPIN_12),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_2
      (configBits[19:18] == 2'h0
         ? IPIN_18
         : configBits[19:18] == 2'h1 ? IPIN_19 : IPIN_20),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_3
      (configBits[19:18] == 2'h0
         ? IPIN_26
         : configBits[19:18] == 2'h1 ? IPIN_27 : IPIN_28),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_outR      (_BLE_2_io_outR),
    .io_outT      (_BLE_2_io_outT),
    .io_gndOuts   (gndLBouts),
    .io_clkEnb    (configBits[162]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:63:38
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_3 (	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[79:60]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:57:38
    .io_in_0
      (configBits[19:18] == 2'h0 ? IPIN_3 : configBits[19:18] == 2'h1 ? IPIN_4 : IPIN_5),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_1
      (configBits[19:18] == 2'h0
         ? IPIN_11
         : configBits[19:18] == 2'h1 ? IPIN_12 : IPIN_13),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_2
      (configBits[19:18] == 2'h0
         ? IPIN_19
         : configBits[19:18] == 2'h1 ? IPIN_20 : IPIN_21),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_3
      (configBits[19:18] == 2'h0
         ? IPIN_27
         : configBits[19:18] == 2'h1 ? IPIN_28 : IPIN_29),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_outR      (_BLE_3_io_outR),
    .io_outT      (_BLE_3_io_outT),
    .io_gndOuts   (gndLBouts),
    .io_clkEnb    (configBits[162]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:63:38
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_4 (	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[99:80]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:57:38
    .io_in_0
      (configBits[19:18] == 2'h0 ? IPIN_4 : configBits[19:18] == 2'h1 ? IPIN_5 : IPIN_6),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_1
      (configBits[19:18] == 2'h0
         ? IPIN_12
         : configBits[19:18] == 2'h1 ? IPIN_13 : IPIN_14),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_2
      (configBits[19:18] == 2'h0
         ? IPIN_20
         : configBits[19:18] == 2'h1 ? IPIN_21 : IPIN_22),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_3
      (configBits[19:18] == 2'h0
         ? IPIN_28
         : configBits[19:18] == 2'h1 ? IPIN_29 : IPIN_30),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_outR      (_BLE_4_io_outR),
    .io_outT      (_BLE_4_io_outT),
    .io_gndOuts   (gndLBouts),
    .io_clkEnb    (configBits[162]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:63:38
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_5 (	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[119:100]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:57:38
    .io_in_0
      (configBits[19:18] == 2'h0 ? IPIN_5 : configBits[19:18] == 2'h1 ? IPIN_6 : IPIN_7),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_1
      (configBits[19:18] == 2'h0
         ? IPIN_13
         : configBits[19:18] == 2'h1 ? IPIN_14 : IPIN_15),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_2
      (configBits[19:18] == 2'h0
         ? IPIN_21
         : configBits[19:18] == 2'h1 ? IPIN_22 : IPIN_23),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_3
      (configBits[19:18] == 2'h0
         ? IPIN_29
         : configBits[19:18] == 2'h1 ? IPIN_30 : IPIN_31),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_outR      (_BLE_5_io_outR),
    .io_outT      (_BLE_5_io_outT),
    .io_gndOuts   (gndLBouts),
    .io_clkEnb    (configBits[162]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:63:38
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_6 (	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[139:120]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:57:38
    .io_in_0
      (configBits[19:18] == 2'h0 ? IPIN_6 : configBits[19:18] == 2'h1 ? IPIN_7 : IPIN_0),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_1
      (configBits[19:18] == 2'h0
         ? IPIN_14
         : configBits[19:18] == 2'h1 ? IPIN_15 : IPIN_8),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_2
      (configBits[19:18] == 2'h0
         ? IPIN_22
         : configBits[19:18] == 2'h1 ? IPIN_23 : IPIN_16),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_3
      (configBits[19:18] == 2'h0
         ? IPIN_30
         : configBits[19:18] == 2'h1 ? IPIN_31 : IPIN_24),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_outR      (_BLE_6_io_outR),
    .io_outT      (_BLE_6_io_outT),
    .io_gndOuts   (gndLBouts),
    .io_clkEnb    (configBits[162]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:63:38
    .io_loopBreak (loopBreak)
  );
  Ble4 BLE_7 (	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:55:48
    .clock        (clock),
    .reset        (reset),
    .io_config    (configBits[159:140]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:57:38
    .io_in_0
      (configBits[19:18] == 2'h0 ? IPIN_7 : configBits[19:18] == 2'h1 ? IPIN_0 : IPIN_1),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_1
      (configBits[19:18] == 2'h0 ? IPIN_15 : configBits[19:18] == 2'h1 ? IPIN_8 : IPIN_9),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_2
      (configBits[19:18] == 2'h0
         ? IPIN_23
         : configBits[19:18] == 2'h1 ? IPIN_16 : IPIN_17),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_in_3
      (configBits[19:18] == 2'h0
         ? IPIN_31
         : configBits[19:18] == 2'h1 ? IPIN_24 : IPIN_25),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :58:{69,114}
    .io_outR      (_BLE_7_io_outR),
    .io_outT      (_BLE_7_io_outT),
    .io_gndOuts   (gndLBouts),
    .io_clkEnb    (configBits[162]),	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:63:38
    .io_loopBreak (loopBreak)
  );
  assign OPIN_41 = configBits[161] ? OMem_0 : _BLE_0_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_42 = configBits[161] ? OMem_1 : _BLE_1_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_43 = configBits[161] ? OMem_2 : _BLE_2_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_44 = configBits[161] ? OMem_3 : _BLE_3_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_45 = configBits[161] ? OMem_4 : _BLE_4_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_46 = configBits[161] ? OMem_5 : _BLE_5_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_47 = configBits[161] ? OMem_6 : _BLE_6_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_48 = configBits[161] ? OMem_7 : _BLE_7_io_outR;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_49 = configBits[161] ? OMem_8 : _BLE_0_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_50 = configBits[161] ? OMem_9 : _BLE_1_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_51 = configBits[161] ? OMem_10 : _BLE_2_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_52 = configBits[161] ? OMem_11 : _BLE_3_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_53 = configBits[161] ? OMem_12 : _BLE_4_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_54 = configBits[161] ? OMem_13 : _BLE_5_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_55 = configBits[161] ? OMem_14 : _BLE_6_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign OPIN_56 = configBits[161] ? OMem_15 : _BLE_7_io_outT;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :40:{15,26}, :48:57, :55:48
  assign ioPad_o =
    configBits[160]
      ? {IPIN_39,
         IPIN_38,
         IPIN_37,
         IPIN_36,
         IPIN_35,
         IPIN_34,
         IPIN_33,
         IPIN_32,
         IPIN_31,
         IPIN_30,
         IPIN_29,
         IPIN_28,
         IPIN_27,
         IPIN_26,
         IPIN_25,
         IPIN_24,
         IPIN_23,
         IPIN_22,
         IPIN_21,
         IPIN_20,
         IPIN_19,
         IPIN_18,
         IPIN_17,
         IPIN_16,
         IPIN_15,
         IPIN_14,
         IPIN_13,
         IPIN_12,
         IPIN_11,
         IPIN_10,
         IPIN_9,
         IPIN_8,
         IPIN_7,
         IPIN_6,
         IPIN_5,
         IPIN_4,
         IPIN_3,
         IPIN_2,
         IPIN_1,
         IPIN_0}
      : braminFF;	// home/kmgroup/projects/tutorial/efpga_basic/src/main/scala/efpga/logicblks/CLBlut4N10Mem.scala:11:7, :45:42, :46:{21,32,57}
endmodule

