//Verilog generated by VPR 8.1.0-dev+7a9676256 from post-place-and-route implementation
module alu_sub (
    input \IN[0] ,
    input \IN[1] ,
    input \IN[2] ,
    input \IN[3] ,
    input \IN[4] ,
    input \IN[5] ,
    input \IN[6] ,
    input \IN[7] ,
    input \IN[8] ,
    input \IN[9] ,
    input \IN[10] ,
    input \IN[11] ,
    input \IN[12] ,
    input \IN[13] ,
    input \IN[14] ,
    input \IN[15] ,
    input \IN[16] ,
    input \IN[17] ,
    input \IN[18] ,
    input \IN[19] ,
    input \IN[20] ,
    input \IN[21] ,
    input \IN[22] ,
    input \IN[23] ,
    input \IN[24] ,
    input \IN[25] ,
    input \IN[26] ,
    input \IN[27] ,
    input \IN[28] ,
    input \IN[29] ,
    input \IN[30] ,
    input \IN[31] ,
    input \clk ,
    output \OUT[32] ,
    output \OUT[33] ,
    output \OUT[34] ,
    output \OUT[35] ,
    output \OUT[36] ,
    output \OUT[37] ,
    output \OUT[38] ,
    output \OUT[39] ,
    output \OUT[40] ,
    output \OUT[41] ,
    output \OUT[42] ,
    output \OUT[43] ,
    output \OUT[44] ,
    output \OUT[45] ,
    output \OUT[46] ,
    output \OUT[47] ,
    output \OUT[0] ,
    output \OUT[1] ,
    output \OUT[2] ,
    output \OUT[3] ,
    output \OUT[4] ,
    output \OUT[5] ,
    output \OUT[6] ,
    output \OUT[7] ,
    output \OUT[8] ,
    output \OUT[9] ,
    output \OUT[10] ,
    output \OUT[11] ,
    output \OUT[12] ,
    output \OUT[13] ,
    output \OUT[14] ,
    output \OUT[15] ,
    output \OUT[16] ,
    output \OUT[17] ,
    output \OUT[18] ,
    output \OUT[19] ,
    output \OUT[20] ,
    output \OUT[21] ,
    output \OUT[22] ,
    output \OUT[23] ,
    output \OUT[24] ,
    output \OUT[25] ,
    output \OUT[26] ,
    output \OUT[27] ,
    output \OUT[28] ,
    output \OUT[29] ,
    output \OUT[30] ,
    output \OUT[31] ,
    output \OUT[48] ,
    output \OUT[49] ,
    output \OUT[50] ,
    output \OUT[51] ,
    output \OUT[52] ,
    output \OUT[53] ,
    output \OUT[54] ,
    output \OUT[55] ,
    output \OUT[56] ,
    output \OUT[57] ,
    output \OUT[58] ,
    output \OUT[59] ,
    output \OUT[60] ,
    output \OUT[61] ,
    output \OUT[62] ,
    output \OUT[63] ,
    output \OUT[64] ,
    output \OUT[65] ,
    output \OUT[66] ,
    output \OUT[67] ,
    output \OUT[68] ,
    output \OUT[69] ,
    output \OUT[70] ,
    output \OUT[71] ,
    output \OUT[72] ,
    output \OUT[73] ,
    output \OUT[74] ,
    output \OUT[75] ,
    output \OUT[76] ,
    output \OUT[77] ,
    output \OUT[78] ,
    output \OUT[79] ,
    output \OUT[80] ,
    output \OUT[81] ,
    output \OUT[82] ,
    output \OUT[83] ,
    output \OUT[84] ,
    output \OUT[85] ,
    output \OUT[86] ,
    output \OUT[87] ,
    output \OUT[88] ,
    output \OUT[89] ,
    output \OUT[90] ,
    output \OUT[91] ,
    output \OUT[92] ,
    output \OUT[93] ,
    output \OUT[94] ,
    output \OUT[95] ,
    output \OUT[96] ,
    output \OUT[97] ,
    output \OUT[98] ,
    output \OUT[99] ,
    output \OUT[100] ,
    output \OUT[101] ,
    output \OUT[102] ,
    output \OUT[103] ,
    output \OUT[104] ,
    output \OUT[105] ,
    output \OUT[106] ,
    output \OUT[107] ,
    output \OUT[108] ,
    output \OUT[109] ,
    output \OUT[110] ,
    output \OUT[111] ,
    output \OUT[112] ,
    output \OUT[113] ,
    output \OUT[114] ,
    output \OUT[115] ,
    output \OUT[116] ,
    output \OUT[117] ,
    output \OUT[118] ,
    output \OUT[119] ,
    output \OUT[120] ,
    output \OUT[121] ,
    output \OUT[122] ,
    output \OUT[123] ,
    output \OUT[124] ,
    output \OUT[125] ,
    output \OUT[126] ,
    output \OUT[127] 
);

    //Wires
    wire \IN[0]_output_0_0 ;
    wire \IN[1]_output_0_0 ;
    wire \IN[2]_output_0_0 ;
    wire \IN[3]_output_0_0 ;
    wire \IN[4]_output_0_0 ;
    wire \IN[5]_output_0_0 ;
    wire \IN[6]_output_0_0 ;
    wire \IN[7]_output_0_0 ;
    wire \IN[8]_output_0_0 ;
    wire \IN[9]_output_0_0 ;
    wire \IN[10]_output_0_0 ;
    wire \IN[11]_output_0_0 ;
    wire \IN[12]_output_0_0 ;
    wire \IN[13]_output_0_0 ;
    wire \IN[14]_output_0_0 ;
    wire \IN[15]_output_0_0 ;
    wire \IN[16]_output_0_0 ;
    wire \IN[17]_output_0_0 ;
    wire \IN[18]_output_0_0 ;
    wire \IN[19]_output_0_0 ;
    wire \IN[20]_output_0_0 ;
    wire \IN[21]_output_0_0 ;
    wire \IN[22]_output_0_0 ;
    wire \IN[23]_output_0_0 ;
    wire \IN[24]_output_0_0 ;
    wire \IN[25]_output_0_0 ;
    wire \IN[26]_output_0_0 ;
    wire \IN[27]_output_0_0 ;
    wire \IN[28]_output_0_0 ;
    wire \IN[29]_output_0_0 ;
    wire \IN[30]_output_0_0 ;
    wire \IN[31]_output_0_0 ;
    wire \clk_output_0_0 ;
    wire \lut_$false_output_0_0 ;
    wire \lut_$undef_output_0_0 ;
    wire \latch_R0_1_output_0_0 ;
    wire \latch_R0_output_0_0 ;
    wire \clbalu_alu_output_0_0 ;
    wire \clbalu_alu_output_0_1 ;
    wire \clbalu_alu_output_0_2 ;
    wire \clbalu_alu_output_0_3 ;
    wire \clbalu_alu_output_0_4 ;
    wire \clbalu_alu_output_0_5 ;
    wire \clbalu_alu_output_0_6 ;
    wire \clbalu_alu_output_0_7 ;
    wire \clbalu_alu_output_0_8 ;
    wire \clbalu_alu_output_0_9 ;
    wire \clbalu_alu_output_0_10 ;
    wire \clbalu_alu_output_0_11 ;
    wire \clbalu_alu_output_0_12 ;
    wire \clbalu_alu_output_0_13 ;
    wire \clbalu_alu_output_0_14 ;
    wire \clbalu_alu_output_0_15 ;
    wire \clbalu_alu_input_0_0 ;
    wire \latch_R0_1_input_0_0 ;
    wire \clbalu_alu_input_0_1 ;
    wire \clbalu_alu_input_0_2 ;
    wire \clbalu_alu_input_0_3 ;
    wire \clbalu_alu_input_0_4 ;
    wire \clbalu_alu_input_0_5 ;
    wire \clbalu_alu_input_0_6 ;
    wire \clbalu_alu_input_0_7 ;
    wire \clbalu_alu_input_0_8 ;
    wire \clbalu_alu_input_0_9 ;
    wire \clbalu_alu_input_0_10 ;
    wire \clbalu_alu_input_0_11 ;
    wire \clbalu_alu_input_0_12 ;
    wire \clbalu_alu_input_0_13 ;
    wire \clbalu_alu_input_0_14 ;
    wire \clbalu_alu_input_0_15 ;
    wire \clbalu_alu_input_1_0 ;
    wire \clbalu_alu_input_1_1 ;
    wire \clbalu_alu_input_1_2 ;
    wire \clbalu_alu_input_1_3 ;
    wire \clbalu_alu_input_1_4 ;
    wire \clbalu_alu_input_1_5 ;
    wire \clbalu_alu_input_1_6 ;
    wire \clbalu_alu_input_1_7 ;
    wire \clbalu_alu_input_1_8 ;
    wire \clbalu_alu_input_1_9 ;
    wire \clbalu_alu_input_1_10 ;
    wire \clbalu_alu_input_1_11 ;
    wire \clbalu_alu_input_1_12 ;
    wire \clbalu_alu_input_1_13 ;
    wire \clbalu_alu_input_1_14 ;
    wire \clbalu_alu_input_1_15 ;
    wire \clbalu_alu_clock_0_0 ;
    wire \latch_R0_1_clock_0_0 ;
    wire \latch_R0_clock_0_0 ;
    wire \clbalu_alu_input_2_0 ;
    wire \clbalu_alu_input_2_1 ;
    wire \clbalu_alu_input_2_2 ;
    wire \clbalu_alu_input_2_3 ;
    wire \clbalu_alu_input_2_4 ;
    wire \clbalu_alu_input_2_5 ;
    wire \clbalu_alu_input_2_6 ;
    wire \clbalu_alu_input_2_7 ;
    wire \OUT[2]_input_0_0 ;
    wire \OUT[3]_input_0_0 ;
    wire \OUT[4]_input_0_0 ;
    wire \OUT[5]_input_0_0 ;
    wire \OUT[6]_input_0_0 ;
    wire \OUT[7]_input_0_0 ;
    wire \OUT[8]_input_0_0 ;
    wire \OUT[9]_input_0_0 ;
    wire \OUT[10]_input_0_0 ;
    wire \OUT[11]_input_0_0 ;
    wire \OUT[12]_input_0_0 ;
    wire \OUT[13]_input_0_0 ;
    wire \OUT[14]_input_0_0 ;
    wire \OUT[15]_input_0_0 ;
    wire \OUT[16]_input_0_0 ;
    wire \OUT[17]_input_0_0 ;
    wire \OUT[18]_input_0_0 ;
    wire \OUT[19]_input_0_0 ;
    wire \OUT[20]_input_0_0 ;
    wire \OUT[21]_input_0_0 ;
    wire \OUT[22]_input_0_0 ;
    wire \OUT[23]_input_0_0 ;
    wire \OUT[24]_input_0_0 ;
    wire \OUT[25]_input_0_0 ;
    wire \OUT[26]_input_0_0 ;
    wire \OUT[27]_input_0_0 ;
    wire \OUT[28]_input_0_0 ;
    wire \OUT[29]_input_0_0 ;
    wire \OUT[30]_input_0_0 ;
    wire \OUT[31]_input_0_0 ;
    wire \OUT[48]_input_0_0 ;
    wire \OUT[49]_input_0_0 ;
    wire \OUT[50]_input_0_0 ;
    wire \OUT[51]_input_0_0 ;
    wire \OUT[52]_input_0_0 ;
    wire \OUT[53]_input_0_0 ;
    wire \OUT[54]_input_0_0 ;
    wire \OUT[55]_input_0_0 ;
    wire \OUT[56]_input_0_0 ;
    wire \OUT[57]_input_0_0 ;
    wire \OUT[58]_input_0_0 ;
    wire \OUT[59]_input_0_0 ;
    wire \OUT[60]_input_0_0 ;
    wire \OUT[61]_input_0_0 ;
    wire \OUT[62]_input_0_0 ;
    wire \OUT[63]_input_0_0 ;
    wire \OUT[64]_input_0_0 ;
    wire \OUT[65]_input_0_0 ;
    wire \OUT[66]_input_0_0 ;
    wire \OUT[67]_input_0_0 ;
    wire \OUT[68]_input_0_0 ;
    wire \OUT[69]_input_0_0 ;
    wire \OUT[70]_input_0_0 ;
    wire \OUT[71]_input_0_0 ;
    wire \OUT[72]_input_0_0 ;
    wire \OUT[73]_input_0_0 ;
    wire \OUT[74]_input_0_0 ;
    wire \OUT[75]_input_0_0 ;
    wire \OUT[76]_input_0_0 ;
    wire \OUT[77]_input_0_0 ;
    wire \OUT[78]_input_0_0 ;
    wire \OUT[79]_input_0_0 ;
    wire \OUT[80]_input_0_0 ;
    wire \OUT[81]_input_0_0 ;
    wire \OUT[82]_input_0_0 ;
    wire \OUT[83]_input_0_0 ;
    wire \OUT[84]_input_0_0 ;
    wire \OUT[85]_input_0_0 ;
    wire \OUT[86]_input_0_0 ;
    wire \OUT[87]_input_0_0 ;
    wire \OUT[88]_input_0_0 ;
    wire \OUT[89]_input_0_0 ;
    wire \OUT[90]_input_0_0 ;
    wire \OUT[91]_input_0_0 ;
    wire \OUT[92]_input_0_0 ;
    wire \OUT[93]_input_0_0 ;
    wire \OUT[94]_input_0_0 ;
    wire \OUT[95]_input_0_0 ;
    wire \OUT[96]_input_0_0 ;
    wire \OUT[97]_input_0_0 ;
    wire \OUT[98]_input_0_0 ;
    wire \OUT[99]_input_0_0 ;
    wire \OUT[100]_input_0_0 ;
    wire \OUT[101]_input_0_0 ;
    wire \OUT[102]_input_0_0 ;
    wire \OUT[103]_input_0_0 ;
    wire \OUT[104]_input_0_0 ;
    wire \OUT[105]_input_0_0 ;
    wire \OUT[106]_input_0_0 ;
    wire \OUT[107]_input_0_0 ;
    wire \OUT[108]_input_0_0 ;
    wire \OUT[109]_input_0_0 ;
    wire \OUT[110]_input_0_0 ;
    wire \OUT[111]_input_0_0 ;
    wire \OUT[112]_input_0_0 ;
    wire \OUT[113]_input_0_0 ;
    wire \OUT[114]_input_0_0 ;
    wire \OUT[115]_input_0_0 ;
    wire \OUT[116]_input_0_0 ;
    wire \OUT[117]_input_0_0 ;
    wire \OUT[118]_input_0_0 ;
    wire \OUT[119]_input_0_0 ;
    wire \OUT[120]_input_0_0 ;
    wire \OUT[121]_input_0_0 ;
    wire \OUT[122]_input_0_0 ;
    wire \OUT[123]_input_0_0 ;
    wire \OUT[124]_input_0_0 ;
    wire \OUT[125]_input_0_0 ;
    wire \OUT[126]_input_0_0 ;
    wire \OUT[127]_input_0_0 ;
    wire \OUT[0]_input_0_0 ;
    wire \latch_R0_input_0_0 ;
    wire \OUT[1]_input_0_0 ;
    wire \OUT[32]_input_0_0 ;
    wire \OUT[33]_input_0_0 ;
    wire \OUT[34]_input_0_0 ;
    wire \OUT[35]_input_0_0 ;
    wire \OUT[36]_input_0_0 ;
    wire \OUT[37]_input_0_0 ;
    wire \OUT[38]_input_0_0 ;
    wire \OUT[39]_input_0_0 ;
    wire \OUT[40]_input_0_0 ;
    wire \OUT[41]_input_0_0 ;
    wire \OUT[42]_input_0_0 ;
    wire \OUT[43]_input_0_0 ;
    wire \OUT[44]_input_0_0 ;
    wire \OUT[45]_input_0_0 ;
    wire \OUT[46]_input_0_0 ;
    wire \OUT[47]_input_0_0 ;

    //IO assignments
    assign \OUT[32]  = \OUT[32]_input_0_0 ;
    assign \OUT[33]  = \OUT[33]_input_0_0 ;
    assign \OUT[34]  = \OUT[34]_input_0_0 ;
    assign \OUT[35]  = \OUT[35]_input_0_0 ;
    assign \OUT[36]  = \OUT[36]_input_0_0 ;
    assign \OUT[37]  = \OUT[37]_input_0_0 ;
    assign \OUT[38]  = \OUT[38]_input_0_0 ;
    assign \OUT[39]  = \OUT[39]_input_0_0 ;
    assign \OUT[40]  = \OUT[40]_input_0_0 ;
    assign \OUT[41]  = \OUT[41]_input_0_0 ;
    assign \OUT[42]  = \OUT[42]_input_0_0 ;
    assign \OUT[43]  = \OUT[43]_input_0_0 ;
    assign \OUT[44]  = \OUT[44]_input_0_0 ;
    assign \OUT[45]  = \OUT[45]_input_0_0 ;
    assign \OUT[46]  = \OUT[46]_input_0_0 ;
    assign \OUT[47]  = \OUT[47]_input_0_0 ;
    assign \OUT[0]  = \OUT[0]_input_0_0 ;
    assign \OUT[1]  = \OUT[1]_input_0_0 ;
    assign \OUT[2]  = \OUT[2]_input_0_0 ;
    assign \OUT[3]  = \OUT[3]_input_0_0 ;
    assign \OUT[4]  = \OUT[4]_input_0_0 ;
    assign \OUT[5]  = \OUT[5]_input_0_0 ;
    assign \OUT[6]  = \OUT[6]_input_0_0 ;
    assign \OUT[7]  = \OUT[7]_input_0_0 ;
    assign \OUT[8]  = \OUT[8]_input_0_0 ;
    assign \OUT[9]  = \OUT[9]_input_0_0 ;
    assign \OUT[10]  = \OUT[10]_input_0_0 ;
    assign \OUT[11]  = \OUT[11]_input_0_0 ;
    assign \OUT[12]  = \OUT[12]_input_0_0 ;
    assign \OUT[13]  = \OUT[13]_input_0_0 ;
    assign \OUT[14]  = \OUT[14]_input_0_0 ;
    assign \OUT[15]  = \OUT[15]_input_0_0 ;
    assign \OUT[16]  = \OUT[16]_input_0_0 ;
    assign \OUT[17]  = \OUT[17]_input_0_0 ;
    assign \OUT[18]  = \OUT[18]_input_0_0 ;
    assign \OUT[19]  = \OUT[19]_input_0_0 ;
    assign \OUT[20]  = \OUT[20]_input_0_0 ;
    assign \OUT[21]  = \OUT[21]_input_0_0 ;
    assign \OUT[22]  = \OUT[22]_input_0_0 ;
    assign \OUT[23]  = \OUT[23]_input_0_0 ;
    assign \OUT[24]  = \OUT[24]_input_0_0 ;
    assign \OUT[25]  = \OUT[25]_input_0_0 ;
    assign \OUT[26]  = \OUT[26]_input_0_0 ;
    assign \OUT[27]  = \OUT[27]_input_0_0 ;
    assign \OUT[28]  = \OUT[28]_input_0_0 ;
    assign \OUT[29]  = \OUT[29]_input_0_0 ;
    assign \OUT[30]  = \OUT[30]_input_0_0 ;
    assign \OUT[31]  = \OUT[31]_input_0_0 ;
    assign \OUT[48]  = \OUT[48]_input_0_0 ;
    assign \OUT[49]  = \OUT[49]_input_0_0 ;
    assign \OUT[50]  = \OUT[50]_input_0_0 ;
    assign \OUT[51]  = \OUT[51]_input_0_0 ;
    assign \OUT[52]  = \OUT[52]_input_0_0 ;
    assign \OUT[53]  = \OUT[53]_input_0_0 ;
    assign \OUT[54]  = \OUT[54]_input_0_0 ;
    assign \OUT[55]  = \OUT[55]_input_0_0 ;
    assign \OUT[56]  = \OUT[56]_input_0_0 ;
    assign \OUT[57]  = \OUT[57]_input_0_0 ;
    assign \OUT[58]  = \OUT[58]_input_0_0 ;
    assign \OUT[59]  = \OUT[59]_input_0_0 ;
    assign \OUT[60]  = \OUT[60]_input_0_0 ;
    assign \OUT[61]  = \OUT[61]_input_0_0 ;
    assign \OUT[62]  = \OUT[62]_input_0_0 ;
    assign \OUT[63]  = \OUT[63]_input_0_0 ;
    assign \OUT[64]  = \OUT[64]_input_0_0 ;
    assign \OUT[65]  = \OUT[65]_input_0_0 ;
    assign \OUT[66]  = \OUT[66]_input_0_0 ;
    assign \OUT[67]  = \OUT[67]_input_0_0 ;
    assign \OUT[68]  = \OUT[68]_input_0_0 ;
    assign \OUT[69]  = \OUT[69]_input_0_0 ;
    assign \OUT[70]  = \OUT[70]_input_0_0 ;
    assign \OUT[71]  = \OUT[71]_input_0_0 ;
    assign \OUT[72]  = \OUT[72]_input_0_0 ;
    assign \OUT[73]  = \OUT[73]_input_0_0 ;
    assign \OUT[74]  = \OUT[74]_input_0_0 ;
    assign \OUT[75]  = \OUT[75]_input_0_0 ;
    assign \OUT[76]  = \OUT[76]_input_0_0 ;
    assign \OUT[77]  = \OUT[77]_input_0_0 ;
    assign \OUT[78]  = \OUT[78]_input_0_0 ;
    assign \OUT[79]  = \OUT[79]_input_0_0 ;
    assign \OUT[80]  = \OUT[80]_input_0_0 ;
    assign \OUT[81]  = \OUT[81]_input_0_0 ;
    assign \OUT[82]  = \OUT[82]_input_0_0 ;
    assign \OUT[83]  = \OUT[83]_input_0_0 ;
    assign \OUT[84]  = \OUT[84]_input_0_0 ;
    assign \OUT[85]  = \OUT[85]_input_0_0 ;
    assign \OUT[86]  = \OUT[86]_input_0_0 ;
    assign \OUT[87]  = \OUT[87]_input_0_0 ;
    assign \OUT[88]  = \OUT[88]_input_0_0 ;
    assign \OUT[89]  = \OUT[89]_input_0_0 ;
    assign \OUT[90]  = \OUT[90]_input_0_0 ;
    assign \OUT[91]  = \OUT[91]_input_0_0 ;
    assign \OUT[92]  = \OUT[92]_input_0_0 ;
    assign \OUT[93]  = \OUT[93]_input_0_0 ;
    assign \OUT[94]  = \OUT[94]_input_0_0 ;
    assign \OUT[95]  = \OUT[95]_input_0_0 ;
    assign \OUT[96]  = \OUT[96]_input_0_0 ;
    assign \OUT[97]  = \OUT[97]_input_0_0 ;
    assign \OUT[98]  = \OUT[98]_input_0_0 ;
    assign \OUT[99]  = \OUT[99]_input_0_0 ;
    assign \OUT[100]  = \OUT[100]_input_0_0 ;
    assign \OUT[101]  = \OUT[101]_input_0_0 ;
    assign \OUT[102]  = \OUT[102]_input_0_0 ;
    assign \OUT[103]  = \OUT[103]_input_0_0 ;
    assign \OUT[104]  = \OUT[104]_input_0_0 ;
    assign \OUT[105]  = \OUT[105]_input_0_0 ;
    assign \OUT[106]  = \OUT[106]_input_0_0 ;
    assign \OUT[107]  = \OUT[107]_input_0_0 ;
    assign \OUT[108]  = \OUT[108]_input_0_0 ;
    assign \OUT[109]  = \OUT[109]_input_0_0 ;
    assign \OUT[110]  = \OUT[110]_input_0_0 ;
    assign \OUT[111]  = \OUT[111]_input_0_0 ;
    assign \OUT[112]  = \OUT[112]_input_0_0 ;
    assign \OUT[113]  = \OUT[113]_input_0_0 ;
    assign \OUT[114]  = \OUT[114]_input_0_0 ;
    assign \OUT[115]  = \OUT[115]_input_0_0 ;
    assign \OUT[116]  = \OUT[116]_input_0_0 ;
    assign \OUT[117]  = \OUT[117]_input_0_0 ;
    assign \OUT[118]  = \OUT[118]_input_0_0 ;
    assign \OUT[119]  = \OUT[119]_input_0_0 ;
    assign \OUT[120]  = \OUT[120]_input_0_0 ;
    assign \OUT[121]  = \OUT[121]_input_0_0 ;
    assign \OUT[122]  = \OUT[122]_input_0_0 ;
    assign \OUT[123]  = \OUT[123]_input_0_0 ;
    assign \OUT[124]  = \OUT[124]_input_0_0 ;
    assign \OUT[125]  = \OUT[125]_input_0_0 ;
    assign \OUT[126]  = \OUT[126]_input_0_0 ;
    assign \OUT[127]  = \OUT[127]_input_0_0 ;
    assign \IN[0]_output_0_0  = \IN[0] ;
    assign \IN[1]_output_0_0  = \IN[1] ;
    assign \IN[2]_output_0_0  = \IN[2] ;
    assign \IN[3]_output_0_0  = \IN[3] ;
    assign \IN[4]_output_0_0  = \IN[4] ;
    assign \IN[5]_output_0_0  = \IN[5] ;
    assign \IN[6]_output_0_0  = \IN[6] ;
    assign \IN[7]_output_0_0  = \IN[7] ;
    assign \IN[8]_output_0_0  = \IN[8] ;
    assign \IN[9]_output_0_0  = \IN[9] ;
    assign \IN[10]_output_0_0  = \IN[10] ;
    assign \IN[11]_output_0_0  = \IN[11] ;
    assign \IN[12]_output_0_0  = \IN[12] ;
    assign \IN[13]_output_0_0  = \IN[13] ;
    assign \IN[14]_output_0_0  = \IN[14] ;
    assign \IN[15]_output_0_0  = \IN[15] ;
    assign \IN[16]_output_0_0  = \IN[16] ;
    assign \IN[17]_output_0_0  = \IN[17] ;
    assign \IN[18]_output_0_0  = \IN[18] ;
    assign \IN[19]_output_0_0  = \IN[19] ;
    assign \IN[20]_output_0_0  = \IN[20] ;
    assign \IN[21]_output_0_0  = \IN[21] ;
    assign \IN[22]_output_0_0  = \IN[22] ;
    assign \IN[23]_output_0_0  = \IN[23] ;
    assign \IN[24]_output_0_0  = \IN[24] ;
    assign \IN[25]_output_0_0  = \IN[25] ;
    assign \IN[26]_output_0_0  = \IN[26] ;
    assign \IN[27]_output_0_0  = \IN[27] ;
    assign \IN[28]_output_0_0  = \IN[28] ;
    assign \IN[29]_output_0_0  = \IN[29] ;
    assign \IN[30]_output_0_0  = \IN[30] ;
    assign \IN[31]_output_0_0  = \IN[31] ;
    assign \clk_output_0_0  = \clk ;

    //Interconnect
    fpga_interconnect \routing_segment_IN[0]_output_0_0_to_clbalu_alu_input_0_0  (
        .datain(\IN[0]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_0 )
    );

    fpga_interconnect \routing_segment_IN[0]_output_0_0_to_latch_R0_1_input_0_0  (
        .datain(\IN[0]_output_0_0 ),
        .dataout(\latch_R0_1_input_0_0 )
    );

    fpga_interconnect \routing_segment_IN[1]_output_0_0_to_clbalu_alu_input_0_1  (
        .datain(\IN[1]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_1 )
    );

    fpga_interconnect \routing_segment_IN[2]_output_0_0_to_clbalu_alu_input_0_2  (
        .datain(\IN[2]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_2 )
    );

    fpga_interconnect \routing_segment_IN[3]_output_0_0_to_clbalu_alu_input_0_3  (
        .datain(\IN[3]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_3 )
    );

    fpga_interconnect \routing_segment_IN[4]_output_0_0_to_clbalu_alu_input_0_4  (
        .datain(\IN[4]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_4 )
    );

    fpga_interconnect \routing_segment_IN[5]_output_0_0_to_clbalu_alu_input_0_5  (
        .datain(\IN[5]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_5 )
    );

    fpga_interconnect \routing_segment_IN[6]_output_0_0_to_clbalu_alu_input_0_6  (
        .datain(\IN[6]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_6 )
    );

    fpga_interconnect \routing_segment_IN[7]_output_0_0_to_clbalu_alu_input_0_7  (
        .datain(\IN[7]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_7 )
    );

    fpga_interconnect \routing_segment_IN[8]_output_0_0_to_clbalu_alu_input_0_8  (
        .datain(\IN[8]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_8 )
    );

    fpga_interconnect \routing_segment_IN[9]_output_0_0_to_clbalu_alu_input_0_9  (
        .datain(\IN[9]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_9 )
    );

    fpga_interconnect \routing_segment_IN[10]_output_0_0_to_clbalu_alu_input_0_10  (
        .datain(\IN[10]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_10 )
    );

    fpga_interconnect \routing_segment_IN[11]_output_0_0_to_clbalu_alu_input_0_11  (
        .datain(\IN[11]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_11 )
    );

    fpga_interconnect \routing_segment_IN[12]_output_0_0_to_clbalu_alu_input_0_12  (
        .datain(\IN[12]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_12 )
    );

    fpga_interconnect \routing_segment_IN[13]_output_0_0_to_clbalu_alu_input_0_13  (
        .datain(\IN[13]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_13 )
    );

    fpga_interconnect \routing_segment_IN[14]_output_0_0_to_clbalu_alu_input_0_14  (
        .datain(\IN[14]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_14 )
    );

    fpga_interconnect \routing_segment_IN[15]_output_0_0_to_clbalu_alu_input_0_15  (
        .datain(\IN[15]_output_0_0 ),
        .dataout(\clbalu_alu_input_0_15 )
    );

    fpga_interconnect \routing_segment_IN[16]_output_0_0_to_clbalu_alu_input_1_0  (
        .datain(\IN[16]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_0 )
    );

    fpga_interconnect \routing_segment_IN[17]_output_0_0_to_clbalu_alu_input_1_1  (
        .datain(\IN[17]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_1 )
    );

    fpga_interconnect \routing_segment_IN[18]_output_0_0_to_clbalu_alu_input_1_2  (
        .datain(\IN[18]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_2 )
    );

    fpga_interconnect \routing_segment_IN[19]_output_0_0_to_clbalu_alu_input_1_3  (
        .datain(\IN[19]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_3 )
    );

    fpga_interconnect \routing_segment_IN[20]_output_0_0_to_clbalu_alu_input_1_4  (
        .datain(\IN[20]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_4 )
    );

    fpga_interconnect \routing_segment_IN[21]_output_0_0_to_clbalu_alu_input_1_5  (
        .datain(\IN[21]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_5 )
    );

    fpga_interconnect \routing_segment_IN[22]_output_0_0_to_clbalu_alu_input_1_6  (
        .datain(\IN[22]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_6 )
    );

    fpga_interconnect \routing_segment_IN[23]_output_0_0_to_clbalu_alu_input_1_7  (
        .datain(\IN[23]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_7 )
    );

    fpga_interconnect \routing_segment_IN[24]_output_0_0_to_clbalu_alu_input_1_8  (
        .datain(\IN[24]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_8 )
    );

    fpga_interconnect \routing_segment_IN[25]_output_0_0_to_clbalu_alu_input_1_9  (
        .datain(\IN[25]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_9 )
    );

    fpga_interconnect \routing_segment_IN[26]_output_0_0_to_clbalu_alu_input_1_10  (
        .datain(\IN[26]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_10 )
    );

    fpga_interconnect \routing_segment_IN[27]_output_0_0_to_clbalu_alu_input_1_11  (
        .datain(\IN[27]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_11 )
    );

    fpga_interconnect \routing_segment_IN[28]_output_0_0_to_clbalu_alu_input_1_12  (
        .datain(\IN[28]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_12 )
    );

    fpga_interconnect \routing_segment_IN[29]_output_0_0_to_clbalu_alu_input_1_13  (
        .datain(\IN[29]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_13 )
    );

    fpga_interconnect \routing_segment_IN[30]_output_0_0_to_clbalu_alu_input_1_14  (
        .datain(\IN[30]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_14 )
    );

    fpga_interconnect \routing_segment_IN[31]_output_0_0_to_clbalu_alu_input_1_15  (
        .datain(\IN[31]_output_0_0 ),
        .dataout(\clbalu_alu_input_1_15 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_clbalu_alu_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\clbalu_alu_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_R0_1_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_R0_1_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_R0_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_R0_clock_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$false_output_0_0_to_clbalu_alu_input_2_0  (
        .datain(\lut_$false_output_0_0 ),
        .dataout(\clbalu_alu_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$false_output_0_0_to_clbalu_alu_input_2_1  (
        .datain(\lut_$false_output_0_0 ),
        .dataout(\clbalu_alu_input_2_1 )
    );

    fpga_interconnect \routing_segment_lut_$false_output_0_0_to_clbalu_alu_input_2_2  (
        .datain(\lut_$false_output_0_0 ),
        .dataout(\clbalu_alu_input_2_2 )
    );

    fpga_interconnect \routing_segment_lut_$false_output_0_0_to_clbalu_alu_input_2_3  (
        .datain(\lut_$false_output_0_0 ),
        .dataout(\clbalu_alu_input_2_3 )
    );

    fpga_interconnect \routing_segment_lut_$false_output_0_0_to_clbalu_alu_input_2_4  (
        .datain(\lut_$false_output_0_0 ),
        .dataout(\clbalu_alu_input_2_4 )
    );

    fpga_interconnect \routing_segment_lut_$false_output_0_0_to_clbalu_alu_input_2_5  (
        .datain(\lut_$false_output_0_0 ),
        .dataout(\clbalu_alu_input_2_5 )
    );

    fpga_interconnect \routing_segment_lut_$false_output_0_0_to_clbalu_alu_input_2_6  (
        .datain(\lut_$false_output_0_0 ),
        .dataout(\clbalu_alu_input_2_6 )
    );

    fpga_interconnect \routing_segment_lut_$false_output_0_0_to_clbalu_alu_input_2_7  (
        .datain(\lut_$false_output_0_0 ),
        .dataout(\clbalu_alu_input_2_7 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[2]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[3]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[4]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[5]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[6]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[7]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[8]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[8]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[9]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[9]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[10]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[10]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[11]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[11]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[12]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[12]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[13]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[13]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[14]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[14]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[15]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[15]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[16]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[16]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[17]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[17]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[18]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[18]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[19]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[19]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[20]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[20]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[21]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[21]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[22]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[22]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[23]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[23]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[24]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[24]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[25]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[25]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[26]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[26]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[27]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[27]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[28]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[28]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[29]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[29]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[30]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[30]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[31]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[31]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[48]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[48]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[49]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[49]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[50]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[50]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[51]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[51]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[52]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[52]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[53]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[53]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[54]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[54]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[55]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[55]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[56]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[56]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[57]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[57]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[58]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[58]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[59]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[59]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[60]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[60]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[61]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[61]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[62]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[62]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[63]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[63]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[64]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[64]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[65]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[65]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[66]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[66]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[67]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[67]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[68]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[68]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[69]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[69]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[70]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[70]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[71]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[71]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[72]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[72]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[73]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[73]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[74]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[74]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[75]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[75]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[76]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[76]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[77]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[77]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[78]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[78]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[79]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[79]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[80]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[80]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[81]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[81]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[82]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[82]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[83]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[83]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[84]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[84]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[85]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[85]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[86]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[86]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[87]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[87]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[88]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[88]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[89]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[89]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[90]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[90]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[91]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[91]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[92]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[92]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[93]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[93]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[94]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[94]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[95]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[95]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[96]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[96]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[97]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[97]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[98]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[98]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[99]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[99]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[100]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[100]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[101]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[101]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[102]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[102]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[103]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[103]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[104]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[104]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[105]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[105]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[106]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[106]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[107]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[107]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[108]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[108]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[109]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[109]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[110]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[110]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[111]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[111]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[112]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[112]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[113]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[113]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[114]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[114]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[115]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[115]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[116]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[116]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[117]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[117]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[118]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[118]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[119]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[119]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[120]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[120]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[121]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[121]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[122]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[122]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[123]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[123]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[124]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[124]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[125]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[125]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[126]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[126]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$undef_output_0_0_to_OUT[127]_input_0_0  (
        .datain(\lut_$undef_output_0_0 ),
        .dataout(\OUT[127]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_R0_1_output_0_0_to_OUT[0]_input_0_0  (
        .datain(\latch_R0_1_output_0_0 ),
        .dataout(\OUT[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_R0_1_output_0_0_to_latch_R0_input_0_0  (
        .datain(\latch_R0_1_output_0_0 ),
        .dataout(\latch_R0_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_R0_output_0_0_to_OUT[1]_input_0_0  (
        .datain(\latch_R0_output_0_0 ),
        .dataout(\OUT[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_0_to_OUT[32]_input_0_0  (
        .datain(\clbalu_alu_output_0_0 ),
        .dataout(\OUT[32]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_1_to_OUT[33]_input_0_0  (
        .datain(\clbalu_alu_output_0_1 ),
        .dataout(\OUT[33]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_2_to_OUT[34]_input_0_0  (
        .datain(\clbalu_alu_output_0_2 ),
        .dataout(\OUT[34]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_3_to_OUT[35]_input_0_0  (
        .datain(\clbalu_alu_output_0_3 ),
        .dataout(\OUT[35]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_4_to_OUT[36]_input_0_0  (
        .datain(\clbalu_alu_output_0_4 ),
        .dataout(\OUT[36]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_5_to_OUT[37]_input_0_0  (
        .datain(\clbalu_alu_output_0_5 ),
        .dataout(\OUT[37]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_6_to_OUT[38]_input_0_0  (
        .datain(\clbalu_alu_output_0_6 ),
        .dataout(\OUT[38]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_7_to_OUT[39]_input_0_0  (
        .datain(\clbalu_alu_output_0_7 ),
        .dataout(\OUT[39]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_8_to_OUT[40]_input_0_0  (
        .datain(\clbalu_alu_output_0_8 ),
        .dataout(\OUT[40]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_9_to_OUT[41]_input_0_0  (
        .datain(\clbalu_alu_output_0_9 ),
        .dataout(\OUT[41]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_10_to_OUT[42]_input_0_0  (
        .datain(\clbalu_alu_output_0_10 ),
        .dataout(\OUT[42]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_11_to_OUT[43]_input_0_0  (
        .datain(\clbalu_alu_output_0_11 ),
        .dataout(\OUT[43]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_12_to_OUT[44]_input_0_0  (
        .datain(\clbalu_alu_output_0_12 ),
        .dataout(\OUT[44]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_13_to_OUT[45]_input_0_0  (
        .datain(\clbalu_alu_output_0_13 ),
        .dataout(\OUT[45]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_14_to_OUT[46]_input_0_0  (
        .datain(\clbalu_alu_output_0_14 ),
        .dataout(\OUT[46]_input_0_0 )
    );

    fpga_interconnect \routing_segment_clbalu_alu_output_0_15_to_OUT[47]_input_0_0  (
        .datain(\clbalu_alu_output_0_15 ),
        .dataout(\OUT[47]_input_0_0 )
    );


    //Cell instances
    clbalu #(
        .MODE_ALU(32'b00000000000000000000000000000001)
    ) \clbalu_alu  (
        .C(\clbalu_alu_clock_0_0 ),
        .CIN(1'bX),
        .CTRL({
            \clbalu_alu_input_2_7 ,
            \clbalu_alu_input_2_6 ,
            \clbalu_alu_input_2_5 ,
            \clbalu_alu_input_2_4 ,
            \clbalu_alu_input_2_3 ,
            \clbalu_alu_input_2_2 ,
            \clbalu_alu_input_2_1 ,
            \clbalu_alu_input_2_0 
         }),
        .I0({
            \clbalu_alu_input_0_15 ,
            \clbalu_alu_input_0_14 ,
            \clbalu_alu_input_0_13 ,
            \clbalu_alu_input_0_12 ,
            \clbalu_alu_input_0_11 ,
            \clbalu_alu_input_0_10 ,
            \clbalu_alu_input_0_9 ,
            \clbalu_alu_input_0_8 ,
            \clbalu_alu_input_0_7 ,
            \clbalu_alu_input_0_6 ,
            \clbalu_alu_input_0_5 ,
            \clbalu_alu_input_0_4 ,
            \clbalu_alu_input_0_3 ,
            \clbalu_alu_input_0_2 ,
            \clbalu_alu_input_0_1 ,
            \clbalu_alu_input_0_0 
         }),
        .I1({
            \clbalu_alu_input_1_15 ,
            \clbalu_alu_input_1_14 ,
            \clbalu_alu_input_1_13 ,
            \clbalu_alu_input_1_12 ,
            \clbalu_alu_input_1_11 ,
            \clbalu_alu_input_1_10 ,
            \clbalu_alu_input_1_9 ,
            \clbalu_alu_input_1_8 ,
            \clbalu_alu_input_1_7 ,
            \clbalu_alu_input_1_6 ,
            \clbalu_alu_input_1_5 ,
            \clbalu_alu_input_1_4 ,
            \clbalu_alu_input_1_3 ,
            \clbalu_alu_input_1_2 ,
            \clbalu_alu_input_1_1 ,
            \clbalu_alu_input_1_0 
         }),
        .R(1'bX),
        .COUT(),
        .Q({
            \clbalu_alu_output_0_15 ,
            \clbalu_alu_output_0_14 ,
            \clbalu_alu_output_0_13 ,
            \clbalu_alu_output_0_12 ,
            \clbalu_alu_output_0_11 ,
            \clbalu_alu_output_0_10 ,
            \clbalu_alu_output_0_9 ,
            \clbalu_alu_output_0_8 ,
            \clbalu_alu_output_0_7 ,
            \clbalu_alu_output_0_6 ,
            \clbalu_alu_output_0_5 ,
            \clbalu_alu_output_0_4 ,
            \clbalu_alu_output_0_3 ,
            \clbalu_alu_output_0_2 ,
            \clbalu_alu_output_0_1 ,
            \clbalu_alu_output_0_0 
         })
    );

    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0000000000000000)
    ) \lut_$false  (
        .in({
            1'bX,
            1'bX,
            1'bX,
            1'bX
         }),
        .out(\lut_$false_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_R0_1  (
        .D(\latch_R0_1_input_0_0 ), 
        .Q(\latch_R0_1_output_0_0 ), 
        .clock(\latch_R0_1_clock_0_0 )
    );
    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_R0  (
        .D(\latch_R0_input_0_0 ), 
        .Q(\latch_R0_output_0_0 ), 
        .clock(\latch_R0_clock_0_0 )
    );
    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0000000000000000)
    ) \lut_$undef  (
        .in({
            1'bX,
            1'bX,
            1'bX,
            1'bX
         }),
        .out(\lut_$undef_output_0_0 )
    );


endmodule
